### ISSUE TITLE
New build workflow with fonts for Android 

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#1051]
- [ ] Add a new build workflow for fonts for Android with yMin + yMax fixed at yMax value="2007" and yMin value="-605"/> 
- [ ] Add a new fixed yMin + yMax check on the Android builds 

- [ ] file path name: `GoogleSansFlex-Regular.ttf`
- [ ] add to the .zip package `-Android` suffix

**Comment by chrissimpkins** [comment]
The GSF v2.5 release on the repository is not suitable for distribution to the Android system.

![Image](https://github.com/user-attachments/assets/3f55bdf1-4e19-42cb-8f0b-800df2a4b956)

We'll need this issue implemented on a build with the design changes in the GSF v2.5 release and all future GS Flex Latin releases, in a build target intended for Android only.  **Please note: We don't want this change in our default builds**.  Default builds should use the default metrics that come out of the compiler. **We can't ship anything to the Android system without these changes.** 

Let's release this as a new GSF v2.6 bug fix point release on this repository next week.  I created a new milestone on the repo for it.  We'll need to figure out how this release implementation works with our Android fallback stack repository builds.  I think that given our decision this week that we ship full GSF Latin to Android, the implementation of Flex for Android belongs here and the GS fallback work will continue in that Android fallback stack repository.

Can we please implement a CI check around this too so that we never produce a GS Flex build for Android system that does not meet this requirement?  It causes significant line spacing regressions in the Android environment and we risk missing system onboarding deadlines if we don't recognize it before Android QA testing teams do.  Ty!

**Comment by chrissimpkins** [comment]
Android uses the file path `GoogleSansFlex-Regular.ttf` for the variable font file on the Android system

**Comment by chrissimpkins** [comment]
> Android uses the file path `GoogleSansFlex-Regular.ttf` for the variable font file on the Android system

Reopening this issue to address this requirement for the Android build file in our next release.  Let's use the font path that Android uses in our build for Android on the repository.  I'll make this adjustment locally with the repository v2.6 release 

@MariannaPaszkowska @RickyDaMa

**Comment by chrissimpkins** [comment]
Confirming that we added the CI checks on the Android build target so that we are sure we never regress on the fixed yMin + yMax metrics?  I don't need to check this on the Android build file before I distribute to Android teams on any future release?

**Comment by RickyDaMa** [comment]
Yes there's a CI check for the Android file metrics: https://github.com/googlefonts/googlesans-flex/pull/1085/commits/aead440ca7ad8f26b518f9ec54213949e74db563

I'll look into getting the file name in the release updated, I left it out initially for speed as our Fontbakery checks rely on names a lot and so using the name `GoogleSansFlex-Regular.ttf` broke a lot of them. With more time now, happy to address this
