### ISSUE TITLE
correction in the open type feature regarding zeroslash.tf

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#1076]
- [ ] add missing code to the the feature code in the sources
- [ ] update tests

**Comment by MariannaPaszkowska** [comment]
@octaviopardo could you please explain what's left to do here?

**Comment by MariannaPaszkowska** [comment]
from Octavio: zeroslash.tf was missing from the tnum feature.
CC @Hoolean we will have to update the test expectations for the v3 too

**Comment by octaviopardo** [comment]
So I did a correction in the open type code regarding the zero slash. The previous tnum feature uses the @FIGURES and the FIGURES_TAB to define the tabular numbersfeature, but because @FIGURES is also used to define the fractions (FIGURES_NUM and FIGURES_DEN) and there is no zeroslash numerator or denominator, I had to include it as a single line of code in the tnum feature instead of adding the zero slash to the @FIGURES and the @FIGURES_TAB classes

![Image](https://github.com/user-attachments/assets/9d4f3359-ddd9-41e0-94a4-eef9287ae4e2)
