### ISSUE TITLE
Design avar1 for wght

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#108]
25 Jan Edit:
We reached a decision today on the approach to the Google Sans Flex weight axis.  We will use linear interpolation across the entire wght axis range.  There will be no weight avar definition. Medium and Bold weights are heavier by design. It is ok to support a different Flex 700 weight vs. the production Google Sans 700 weight @ opsz 18 in the new family. 

23 Jan EDIT:

- [ ] ~and add avar to match the Medium weight.~ 
- [ ] ~Matching Bold~ - it will depend on the design decision. Is there a strong rationale for keeping the Bold in GS Flex bolder than it is defined in GS? @dberlow 

CC @chrissimpkins @davelab6 

avar1 in Google Sans: https://github.com/googlefonts/googlesans/discussions/278

**Comment by davelab6** [comment]
Can you post a description of the avar1 (not 2 lol) tables in Roboto Flex, Roboto Serif, Amstelvar, Literata, Merriweather, Source Serif 4

- https://github.com/googlefonts/roboto-flex/tree/master/fonts
- https://github.com/googlefonts/roboto-serif/releases
- https://github.com/googlefonts/amstelvar/tree/master/fonts
- https://github.com/googlefonts/literata/tree/main/fonts/variable
- https://github.com/SorkinType/Merriweather/tree/master/fonts/variable 
- https://github.com/adobe-fonts/source-serif/tree/release/VAR

**Comment by chrissimpkins** [comment]
I think that this topic was meant to be avar1?

**Comment by chrissimpkins** [comment]
Background on our weight avar definition in Google Sans. Not a recommendation that we should adopt this in GS Flex.  Rather, surfacing so that we can understand how weight might differ as a team transitions from GS to GS Flex with / without a new avar1 definition on the Flex weight axis.

https://github.com/googlefonts/googlesans/issues/273

**Comment by MariannaPaszkowska** [comment]
Thanks @chrissimpkins! Yes, this issue is about avar1. 
@davelab6 Here are the descriptions of the avar tables in in Roboto Flex, Roboto Serif, Amstelvar, Literata, Merriweather, Source Serif 4. In the _Details_ section, I omitted those subtables that were not remapping anything.

Descriptions:
**SourceSerif4**
Available axes:
\- Optical Size
\- Weight

• avar adjustment on Weight

Details:

```
  <avar>
    <segment axis="wght">
      <mapping from="-1.0" to="-1.0"/>
      <mapping from="-0.5" to="-0.63196"/>
      <mapping from="0.0" to="0.0"/>
      <mapping from="0.4" to="0.33"/>
      <mapping from="0.6" to="0.70795"/>
      <mapping from="1.0" to="1.0"/>
  </avar>
```

**Merriweather**
Available axes:
\- Weight
\- Width
\- Optical Size

• avar adjustment on Weight and Optical Size

Details:

```
  <avar>
    <segment axis="wght">
      <mapping from="-1.0" to="-1.0"/>
      <mapping from="0.0" to="0.0"/>
      <mapping from="0.1667" to="0.28174"/>
      <mapping from="0.6667" to="0.72375"/>
      <mapping from="1.0" to="1.0"/>
    </segment>
    <segment axis="opsz">
      <mapping from="-1.0" to="-1.0"/>
      <mapping from="0.0" to="0.0"/>
      <mapping from="0.0365" to="0.1679"/>
      <mapping from="0.29926" to="0.38684"/>
      <mapping from="0.4744" to="0.60583"/>
      <mapping from="0.73724" to="0.73724"/>
      <mapping from="1.0" to="1.0"/>
    </segment>
  </avar>
  ```


**Literata**
Available axes:
\- Weight
\- Optical Size

• avar adjustment on Weight and Optical Size

Details:

```
  <avar>
    <segment axis="wght">
      <mapping from="-1.0" to="-1.0"/>
      <mapping from="-0.5" to="-0.5"/>
      <mapping from="0.0" to="0.0"/>
      <mapping from="0.2" to="0.16"/>
      <mapping from="0.4" to="0.3"/>
      <mapping from="0.6" to="0.5"/>
      <mapping from="0.8" to="0.8"/>
      <mapping from="1.0" to="1.0"/>
    </segment>
    <segment axis="opsz">
      <mapping from="-1.0" to="-1.0"/>
      <mapping from="0.0" to="0.0"/>
      <mapping from="0.4" to="0.3358"/>
      <mapping from="1.0" to="1.0"/>
    </segment>
  </avar>
```

**Amstervar**
Available axes:
\- Weight
\- Width
\- Optical Size
\- GRAD
\- XTRA
\- XOPQ
\- YOPQ
\- YTLC
\- YTUC
\- YTAS
\- YTDE
\- YTFI

• avar adjustment on Optical Size

Details:
```
  <avar>
    </segment>
    <segment axis="opsz">
      <mapping from="-1.0" to="-1.0"/>
      <mapping from="0.0" to="0.0"/>
      <mapping from="0.0769" to="0.077"/>
      <mapping from="0.16925" to="0.492"/>
      <mapping from="0.53845" to="0.946"/>
      <mapping from="1.0" to="1.0"/>
    </segment>
  </avar>
```
  


**Roboto Flex**
Available axes:
\- Weight
\- Width
\- Optical Size
\- GRAD
\- slnt
\- XTRA
\- XOPQ
\- YOPQ
\- YTLC
\- YTUC
\- YTAS
\- YTDE
\- YTFI

• avar adjustment on Optical Size

Details:
```
  <avar>
    </segment>
    <segment axis="opsz">
      <mapping from="-1.0" to="-1.0"/>
      <mapping from="0.0" to="0.0"/>
      <mapping from="0.0769" to="0.077"/>
      <mapping from="0.16925" to="0.492"/>
      <mapping from="0.53845" to="0.946"/>
      <mapping from="1.0" to="1.0"/>
    </segment>
  </avar>
```

**Comment by davelab6** [comment]
How curious SS4 has no avar1 on opsz.. but yes, this suggests to me that I would expect avar1 tables for at least wght and opsz, although on the call today @dberlow made a case that with sufficient (intermediate) masters it may not be needed. 

The AI from the meeting was for @MariannaPaszkowska to carefully review proofs in the coming weeks and indicate if the shape of the design space requires avar1 smoothing.

**Comment by dberlow** [comment]
Below are image of the other wght ramps, before (left) and after (right), leveling the weights out, (and uncovering another Chrome or Typetools bug).

All the leveling that's required is in the light end of the ramps, where the weight  at the larger sizes comes in too fast because of the huge amount of variation along that axis for 3 sources to control.
<img width="1860" alt="GSF Leveling 100" src="https://user-images.githubusercontent.com/1956494/183920340-bdd893fe-68be-4051-ac58-751e2361b05b.png">
<img width="1863" alt="GSF Leveling 200" src="https://user-images.githubusercontent.com/1956494/183920379-aa7abf8a-ba1a-457e-8382-2b7b23372227.png">
<img width="1864" alt="GSF Leveling 300" src="https://user-images.githubusercontent.com/1956494/183920401-df609606-805e-41e6-94cd-b0c7ca5ca7c4.png">
<img width="1848" alt="GSF Leveling 400" src="https://user-images.githubusercontent.com/1956494/183920459-32b5f855-c5f9-4b3d-8d4d-e5005a4baeaa.png">
<img width="1859" alt="GSF Leveling 500" src="https://user-images.githubusercontent.com/1956494/183920511-2663a637-7748-443e-a656-89be145e34b4.png">
<img width="1860" alt="GSF Leveling 600" src="https://user-images.githubusercontent.com/1956494/183920547-426cb72d-b0e7-4744-853d-19f9fa1a73f1.png">
<img width="1861" alt="GSF Leveling 700" src="https://user-images.githubusercontent.com/1956494/183920577-0f7224b3-00ad-41ac-96a2-d5a339689341.png">
<img width="1860" alt="GSF Leveling 800" src="https://user-images.githubusercontent.com/1956494/183920648-7da8feea-9b12-4b56-8785-cda22dc90b20.png">
<img width="1856" alt="GSF Leveling 900" src="https://user-images.githubusercontent.com/1956494/183920686-0d23ce41-cc53-454a-ad9e-4d8a4c0892f2.png">
<img width="1860" alt="GSF Leveling 1000" src="https://user-images.githubusercontent.com/1956494/183920725-b244dfe3-21f5-4646-b0ad-5f46434e42d0.png">

**Comment by chrissimpkins** [comment]
avar axis map planning from Font Bureau team is taking place in https://docs.google.com/spreadsheets/d/17JHgjAl1QNBgU31JZBDfbwZkUYgm9Z3PIskqBtF1Uns/edit#gid=0

Requested background/context in this thread on how they intend to approach avar tables across the axes proposed in that document

**Comment by MariannaPaszkowska** [comment]
#215

**Comment by MariannaPaszkowska** [comment]
Avar decision: 

- ~we will move the Regular master at opsz 18 to 380 wght (it should match Google Sans exactly in color and glyph widths)~
- [ ] and add avar to match the Medium weight. 
- [ ] Matching Bold - it will depend on the design decision. Is there a strong rationale for keeping the Bold in GS Flex bolder than it is defined in GS? @dberlow 

CC @chrissimpkins @davelab6

**Comment by dberlow** [comment]
There is a rationale for keeping the Bold in GS Flex bolder than it is defined in GS. 

That rational particular to this issue, was originally based on the difficulty of getting a convincing wght in between GS 500 and 700. 

That is illustrated in the attached pdf.

Page 1,
column 1 shows GSF wghts 400, 500, 700 and 900 in GSF, 

column 2 shows wghts 400, 500 and 700 in GS, and 

column 3 shows the wghts GSF needs to change to to match GS. 400, 500 and 700. 

Page 2 then shows that it's not easy to define any wghts between 500 and 700 in GSF as it matched GS, because, why bother if there were not going to be any in GS;)

GSF was tasked with putting as much wght on opsz18 as possible, up to wght1000, and removing as much as possible down to wght1. 

That's a different range allowing all the 100 wght intervals of wght to be distinct. 

[GS vs GSF wght.pdf](https://github.com/googlefonts/googlesans-flex/files/10484479/GS.vs.GSF.wght.pdf)

**Comment by dberlow** [comment]
Below are specimens comparing GS Flex to Roboto Flex with the wghts and sizes of each shown in blue on the right of each ramp.
<img width="633" alt="Screen Shot 2023-01-24 at 4 06 32 PM" src="https://user-images.githubusercontent.com/1956494/214415713-cd9947dc-73a5-4132-960e-21986797deb9.png">

<img width="594" alt="Screen Shot 2023-01-24 at 4 08 03 PM" src="https://user-images.githubusercontent.com/1956494/214416124-3cd4df93-fb6f-4bb4-bb9d-7b24363d4911.png">

**Comment by MariannaPaszkowska** [comment]
Thank you, @dberlow!

**Comment by MariannaPaszkowska** [comment]
We reached a decision today on the approach to the Google Sans Flex weight axis.  We will use linear interpolation across the entire wght axis range.  There will be no weight avar definition. Medium and Bold weights are heavier by design. It is ok to support a different Flex 700 weight vs. the production Google Sans 700 weight @ opsz 18 in the new family.

**Comment by dberlow** [comment]
To be clear, wght is two linear interpolations;
1. 400 down to 1.
2. 400 up to 1000.
They were defined at the possible range those two poles could be from the 400, the weight that needed to remain consistent with the weights of GS 400 and Roboto 400.
Thanks.
