### ISSUE TITLE
Prep for release v3.000 - add design refinements and changes log

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#1091]
Please add the document with the reported design refinements and changes.

**Comment by octaviopardo** [comment]
Due to the new structure of points, we have reviewed the diffenator tests to make sure that all the changes reported were "controlled". I m dividing the report into 4 parts. First, the glyphs we've touched due to different issues, and show up in almost every report of the diffenator:
- Hbar: There were some issues with the referenced sidebearings, especially with the grades. Those have been manually reviewed and fixed
- hbar: There were some issues with the referenced sidebearings, especially with the grades. Those have been manually reviewed and fixed
- Lslash & lslash: there were some issues with the referenced sidebearings, especially in the grades. Those have been manually reviewed and fixed
- ligatures: We have changed the structural composition of the ligatures (from paths to components) to reduce file size. As a consequence, their structure has seen changes that range from hard to perceive to more or less obvious (especially in the heaviest and largest styles, that on the other hand should make much-less-to-none use of ligatures)
- lessequal and greater equal: we have reviewed the alignemt of the components, because they were systematically unaligend along the entire designspace
- combining accents: some combining accents have been centered in the box as good practice. That is why they might show up in the report but not the combined marks

**Comment by octaviopardo** [comment]
Opsz 6 adjustments in diffenator

**OPSZ6 WEIGHT 1**

6-25-1-GD0 RND0 SL-10
H one unit difference to make symmetrical LSB and RSB
onesubscript: smooth diagonal
    
6-25-1-GD0 RND0
commaaccent well centered and relocated in all the letters
iogonek has no changes
    
6-25-1-GD0 RND100 SL-10
fivesuperscript, fivesubscript: same position as sharp for shared nodes
    
6-25-1-GD0 RND100
comma accent well centered and relocated in all letters
    
6-25-1-GD100 RND0 SL-10
Backslash: smooth diagonal
    
6-25-1-GD100 RND0
Fivesuperscript, fivesubscript: same position of shared nodes as Round
    
6-25-1-GD100 RND100 SL-10
fivesuperscript, fivesubscript: same position as sharp for shared nodes
    
6-25-1-GD100 RND100    
eogonek: small adjustment ogonek position

----------


6-100-1-GD0 RND0 SL-10
commaaccent: recentered and adjusted
dotaccentcomb: is ok in v3.0 (was missplaced in v2.6)
        
6-100-1-GD0 RND0
Brace: same shape top and bottom curve
    
6-100-1-GD0 RND100 SL-10
dotaccentcomb is ok in v3.0 (was missplaced in v2.6)
commaaccent: recentered and adjusted
fivesuperscript, fivesubscript: same position of shared nodes as sharp
    
6-100-1-GD0 RND100
Schwa rounded differs from sharp master in 2.6 In 3.0 its corrected.
    
6-100-1-GD100 RND0 SL-10
threesuperscript, threesubscript: same position as round
dotaccentcomb: is ok in v3.0 (was missplaced in v2.6)
fivesuperscript, fivesubscript: same position as round
l: 1 unit deviation due to new point structure
threequarters: auto aligment. correct alignment in threedenominator affect sidebearings of threequarters
l caron auto adjustment activate in v3.0 
Ldot: the dot shifts possition but its a correction from 2.6
    
6-100-1-GD100 RND0
k : upper diagonal was wrong in v2.6
    
6-100-1-GD100 RND100 SL-10
dotaccentcomb : is ok in v3.0 (was missplaced in v2.6)

6-100-1-GD100 RND100
k : upper diagonal was wrong in v2.6
Ə: in v3.0 top part matches sharp in v2.6 they differ. 
fivesubscript: same position as sharp

--------

6-151-1-GD0 RND0 SL-10
x: better consistency in stroke thickness
     
6-151-1-GD0 RND 0
6-151-1-GD0 RND100 SL-10
x: better consistency in stroke thickness
     
6-151-1-GD0 RND100
6-151-1-GD100-RD0- SL-10
threesupercript, threesuperscript: same position as round
multiply: no changes
l, ldot: no changes
    
6-151-1-GD100 RND0
euro: same position as round
    
6-151-1-GD100 RND100 SL-10
onesubscript: better round corner
    
6-151-1-GD100 RND100
k, khook : upper diagonal is ok in v3.0 (was wrong in v2.4)
Itilde: 1 unit correction in the tildecomb


OPSZ6 WEIGHT 400
    
6-25-400-GD0 RND0 SL-10
6-25-400-GD0 RND0
I version 3.0 has the anchor centered 2.6 doesnt
    
6-25-400-GD0 RND100 SL-10
dollar: same position of shared nodes as sharp
    
6-25-400-GD0 RND100
I version 3.0 has the anchor centered 2.6 doesnt
    
6-25-400-GD100 RND0 SL-10
section: same position as round
(if s letters show up, they have no changes :P)
    
6-25-400-GD100 RND0
threesuperscript: same position as Round
exclamdown no changes
        
6-25-400-GD100 RND100 SL-10
dollar: same position as sharp
    
6-25-400-GD100 RND100
dollar: same position of shared nodes as sharp
no changes in eth

----------

6-100-400-GD0 RND0 SL-10
fivesubscript: same position as Round
commaaccent: well centered
dotaccentcomb: is ok in v3.0 (was missplaced in v2.6)
l: no changes
    
6-100-400-GD0 RND0
6-100-400-GD0 RND100 SL-10
x: extended diagonals to reduce extra white space created by rounding
k: design adjusted to work better
dotaccentcomb: is ok in v3.0 (was missplaced in v2.4)
commaaccent wel adjusted
    
6-100-400-GD0 RND100
k: extended diagonals to reduce extra white space created by rounding
    
6-100-400-GD100 RND0 SL-10
commaaccent: well centered
dotaccentcomb: is ok in v3.0 (was missplaced in v2.6)
R/Rcaron:changes because of the new structure
Q: reviewed
eth: top bar is correctly placed in v3.0
    
 6-100-400-GD100 RND0
Bhook: corrected in v3.0
Dhook: corrected in v3.0
dcroat: proportions are correct in v3.0
    
6-100-400-GD100 RND100 SL-10
k, khook, x: diagonals are extended to reduce white space caused by rounding
commaaccent: well centedered
dotaccentcomb: is ok in v3.0 (was missplaced in v2.6)
Q: fix in v3.0
eth: bar adjusted to sharp
    
6-100-400-GD100 RND100
Bhook: corrected in v3.0
Dhook: corrected in v3.0
k, khook, x: diagonals are extended in v3.0 to reduce white space created by rounding
dcroat: proportions are correct in v3.0
commaaccent: ligera corrección posición

-----------

6-151-400-GD0 RND0 SL-10
I: has the anchor centered in v3.0 but not in v2.4
    
6-151-400-GD0 RND0
I: has the anchor centered in v3.0 but not in v2.4
    
6-151-400-GD0 RND100 SL-10
k, khook : diagonals are slightly extended in v3.0 to reduce extra white space caused by rounding
        
6-151-400-GD0 RND100
dollar: same position of shared nodes as sharp
I: has the anchor centered in v3.0 but not in v2.4
    
6-151-400-GD100 RND0 SL-10
threesubscript: same position as Round
Q adjusted
    
6-151-400-GD100 RND0    
6-151-400-GD100 RND100 SL-10
section: same positon as sharp
fivesubscript, fivesuperscript: same position as sharp
braceright: same position for shared nodes as sharp
    
6-151-400-GD100 RND100
section: same position as sharp

-----------

6-25-1000-GD0 RND0 SL-10
lcommaaccent we see no changes
    
6-25-1000-GD0 RND0
guilemetright: smooth diagonals, new corner nodes position
    
6-25-1000-GD0 RND100 SL-10
yhook in 2.6 has incorrect spacing that does not match the sharp or grade0 
    
6-25-1000-GD0 RND100
k: upper diagonal is too thin in v2.4. Corrected in v3.0
    
6-25-1000-GD100 RND0 SL-10
Dhook Bhook** are the same width in grade 100 in 3.0 not in 2.4 
fivesuperscript, fivesubscript: same position as Round
lcommaaccent: is OK but it is still in the report (?)
    
6-25-1000-GD100 RND0
Dhook Bhook are the same width in grade 100 in 3.0 not in 2.4 
commaaccent slightly adjusted    
    
6-25-1000-GD100 RND100 SL-10
Dhook Bhook are the same width in grade 100 in 3.0 not in 2.4 
    
6-25-1000-GD100 RND100
Dhook Bhook are the same width in grade 100 in 3.0 not in 2.4
commaaccent adjusted

-----------

6-100-1000-GD0 RND0 SL-10
commaaccent: corrected
dcroat proportions are wrong in v2.6. Corrected in v3.0
dotaccentcomb: is ok in v3.0 (was misplaced in v2.6)
fivesuperscript, fivesubscript: same position as Round
    
6-100-1000-GD0 RND0
dcroat was too wide compared to d in v2.6. Corrected in v3.0
onesuperscript: has no changes
    
6-100-1000-GD0 RND100 SL-10
x design adjusted
commaaccent adjusted
dotaccent adjusted
IJ has nothing
    
6-100-1000-GD0 RND100
dcroat was too wide compared to d in v2.4. Corrected in v3.0
    
6-100-1000-GD100 RND0 SL-10
commaaccent adjusted
dcroat proportions are wrong in v2.4. Corrected in v3.0
fivesuperscript, fivesubscript: same position as Round
dotaccentcomb: is ok in v3.0 (was missplaced in v2.4)
Bhook Dhook in version 2.6, g100 was misplaced compared with g0. corrected
braceright: smooth middle curves, new round
    
6-100-1000-GD100 RND0
dcroat was too wide compared to d in v2.6. Corrected in v3.0
Bhook Dhook, habia diferencias entre G0 y G100
onesuperscript: no changes
g top anchor slightly adjusted    
    
6-100-1000-GD100 RND100 SL-10
dcroat proportions are wrong in v2.6 Corrected in v3.0
Bhook Dhook v2.4 was wrong in between G0 & G100. Corrected
dotaccentcomb: is ok in v3.0 (was missplaced in v2.6)
commaaccent adjusted
no differencs in IJ
    
6-100-1000-GD100 RND100
dcroat proportions are wrong in v2.6. Corrected in v3.0
yhook: improovement of spacing
Bhook Dhook grade in 2.6 was wrong. metrics adjusted
commaaccent adjusted
g top anchor adjusted

------------

6-151-1000-GD0 RND0 SL-10
6-151-1000-GD0 RND0
6-151-1000-GD0 RND100 SL-10
Fivedenominator: terminación Round algo más larga. Same position as sharp
    
6-151-1000-GD0 RND100
6-151-1000-GD100 RND0 SL-10
6-151-1000-GD100 RND0
6-151-1000-GD100 RND100 SL-10
Fivedenominator: terminación Round algo más larga. Same position as sharp
yhook in 2.4 badly placed
if w and accents show up in the report, we do not understand why. We see no changes
    
6-151-1000-GD100 RND100
yhook spacing adjusted

**Comment by octaviopardo** [comment]
Opsz18

18-25-1-GD0 RD0 SL-10
sevensubscript: smooth diagonal
onesubscript: smooth diagonal
Acircumacute and Ycircumflex have no differences
    
18-25-1-GD0 RD0
X: Not  major changes the differing pixel % its due the new point positioning in the diagonals that change very slightly.
y: no differences. Should not be in the report
A: no major changes. New point positioning in the diagonals that change very slightly. Ogonek had a bump
    
18-25-1-GD0  RD100 SL-10
G: Its matching sharp in v3.0 the difference in v2.4 between sharp and rounded was too great.   
C: Its matching sharp in v3.0 the difference in v2.4 between sharp and rounded was too great.
Schwa: Its matching sharp in v3.0 the difference in v2.4 between sharp and rounded was too great.
    
18-25-1-GD0 RD100
18-25-1-GD100 RD0 SL-10
percent: better distribution of space
paragraph: should not be in the report
    
18-25-1-GD100 RD0
braceright: smooth middle curves, new round
A with diacritics: I don't see any major changes. Only the diagonals change a bit for the new point position.
foursubscript: smooth diagonal
    
18-25-1-GD100  RD100 SL-10
percent: better distribution of space
Euro: smooth terminals of horizontal bars, new round
Y fix bug in contour
Oslash corrected shape in 3.0
    
18-25-1-GD100 RD100
Bar in dollar changed

------------

18-100-1-GD0 RD0 SL-10
18-100-1-GD0 RD0
18-100-1-GD0 RD100 SL-10
18-100-1-GD0 RD100
18-100-1-GD100 RD0 SL-10
l,lcaron, lslash, and lcommaaccent are ok. Should not be in the report.
backslash: bottom stroke moved 1 unit to fit with the sidebearings of sharp
    
18-100-1-GD100 RD0
Braceright: smooth middle curves, new round
    
18-100-1-GD100 RD100 SL-10
q is fine, should not be in the report
    
18-100-1-GD100 RD100
dollar: same position as sharp

-------------

18-151-1-GD0 RD0 SL-10
Zeroslash: new angle of slash
l, lcommaaccent: new node structure makes the shape slightly different. There is no solution for this.
    
18-151-1-GD0 RD0
Zeroslash: new angle of slash
    
18-151-1-GD0 RD100 SL-10
Zeroslash: new angle of slash
    
18-151-1-GD0 RD100
Zeroslash: new angle of slash
    
18-151-1-GD100 RD0 SL-10
Zeroslash: new angle of slash
       
18-151-1-GD100 RD0
braceright, braceleft: symmetric top and bottom half
Zeroslash: new angle of slash
    
18-151-1-GD100 RD100 SL-10
 Zeroslash: new angle of slash
    
18-151-1-GD100 RD100
Zeroslash: new angle of slash
braceright, braceleft: symmetric top and bottom half

-----------

OPSZ18 WGTH 400

18-25-400-GD RD0 SL-10
sevensubscript: smooth diagonals
braceright: smooth middle curves, new round
    
18-25-400-GD0 RD0
dollar, cent: same thickness of vertical stroke as slanted
Q improved in v3.0
braceleft: smooth middle curves, new rounder
we see no changes in exclam
    
18-25-400-GD0 RD100- SL-10
Oslash had a bug on 2.4 corrected the angle in 3.0 between sharp and rounded. 
    
18-25-400-GD0 RD100
radical was placed in a different position than sharp in 2.6
dollar: same position of shared nodes as sharp
t : we have improved the rounding of middle bar in  3.0
cent: same thickness of vertical stroke as slanted and dollar
z: new round, improved corners 
sevensuperscript: improved round joint, new rounder
braceright: smooth middle curves, new rounder
       
18-25-400-GD100 RD0 SL-10
Z top right corner had a bump in v2.4
Q corrected in v3.0
    
18-25-400-GD100 RD0
germandbls stem adjusted properly
    
18-25-400-GD100 RD100 SL-10
Schwa corrected in rounded to match sharp
Q corrected in 3.0

18-25-400-GD100 RD100 (Juanlu)
z: new round, improved corners 
Q corrected in v3.0
braceleft: smooth middle curves, new rounder
 
-------------

18-100-400-GD0 RD0 SL-10
l we see no changes
    
18-100-400-GD0 RD0
18-100-400-GD0 RD100 SL-10
18-100-400-GD0 RD100
18-100-400-GD100 RD0 SL-10
y is ok. Slight variation of thickness in right diagonal caused by new node structure
    
18-100-400-GD100 RD0
Braceright: smooth middle curves, new rounder
    
18-100-400-GD100 RD100 SL-10
Braceright, braceleft: smooth middle curves, new rounder
    
18-100-400-GD100 RD100 (Juanlu)

---------

18-151-400-GD0 RD0 SL-10
Khook linked to H on the left in 3.0 makes the difference in positioning vs 2.6 (bug in linked metrics)
    
18-151-400-GD0 RD0
Two: horizontal bar aligned to the baseline, OK 3.0
Zeroslash: new slash angle 
    
18-151-400-GD0 RD100 -10
y: better position for the nodes in the joint of diagonals
    
18-151-400-GD0 RD100
Two: horizontal bar aligned to the baseline, OK 3.0
Zeroslash: new slash angle 
    
18-151-400-GD100 RD0 SL-10
Dollar, cent: improved stroke thickness
Q: improved in 3.0
    
18-151-400-GD100 RD0
Dollar, cent: improved stroke thickness
Zeroslash: new slash angle
Two: horizontal bar aligned to the baseline, OK 3.0

18-151-400-GD100 RD100 SL-10 (Juanlu)
Dollar, cent: improved stroke thickness
Question: same position as sharp
    
18-151-400-GD100 RD100
Dollar, cent: improved stroke thickness 
Two: horizontal bar aligned to the baseline, OK 3.0
acutecomb grave design changed

---------

OPSZ18 WGTH1000

18-25-1000-GD0 RD0 SL-10
fivesubscript, fivesuperscript: same posicion as round
commaaccent adjusted
    
18-25-1000-GD0 RD0
18-25-1000-GD0 RD100 SL-10
threesubscript, threesuperscript: same position as sharp
Two: longer top terminal, matches better with Sharp
e: longer bottom terminal, matches better with sharp
commaaccent adjusted
threequarters: affected by threesuperscript position
        
18-25-1000-GD0 RD100
18-25-1000-GD100 RD0 SL-10
fivesubscript, fivesuperscript: same posicion as round
cent: same position as GD0, OK v3.0
commaaccent adjusted
    
18-25-1000-GD100 RD0
18-25-1000-GD100 RD100 SL-10
threesubscript, threesuperscript: same position as sharp
Two: longer top terminal, matches better with Sharp
e: longer bottom terminal, matches better with sharp
commaaccent adjusted
threequarters: affected by threesuperscript position
    
- 18-25-1000-GD100 RD100
fivesubscript, fivesuperscript: same posicion as round
    
----------

18-100-1000-GD0 RD0 SL-10
18-100-1000-GD0 RD0
Two: better top curve to match Round

18-100-1000-GD0 RD100 SL-10
u: bottom anchor same position as sharp
Two: longer top terminal to match Upright
    
18-100-1000-GD0 RD100
Two: shorter top terminal to match Slanted
j: stem is 10 units thicker in 2.4. Corrected in 3.0
        
18-100-1000-GD100 RD0 SL-10
18-100-1000-GD100 RD0
Two: better top curve to match Round
Abreve has no changes
    
18-100-1000-GD100 RD100 SL-10
Two: longer top terminal to match Upright
 braceleft new rounding
    
18-100-1000-GD100 RD100
j: stem is 10 units thicker in 2.4. Corrected in 3.0
Two: longer top terminal to match Upright

-----------

18-151-1000-GD0 RD0 SL-10
x: smooth diagonals (might disappear from report)
        
18-151-1000-GD0 RD0
X change in v3.0 due the new point positioning
xvy, chages from new structure (may disappear)
        
18-151-1000-GD0 RD100 SL-10
y: improved terminal of the short diagonal and correct position of top anchor
    
18-151-1000-GD0 RD100
y: improved terminal of the short diagonal and correct positon of top anchor
    
18-151-1000-GD100 RD0 SL-10
18-151-1000-GD100 RD0
we see no changes in yv
    
18-151-1000-GD100 RD100 SL-10
y: improved terminal of the short diagonal and correct position of top anchor
    
18-151-1000-GD100 RD100 (Juanlu)
y: improved terminal of the short diagonal and correct position of top anchor

**Comment by octaviopardo** [comment]
OPSZ144

WGTH 1

144-25-1-GD0 RD0 SL-10
Six, Nine: improved strokes joint
M the new point structure limits the position and changes a bit
sevensubscript: smooth diagonals, new rounder
onequarter, onehalf, threequarters: smooth diagonals. It might not appear in the report.
    
144-25-1-GD0 RD0
Six, Nine: improved strokes joint
M the new point structure limits the position and changes a bit
N and Ncaron the new point structure limits the position and changes a bit
onehalf, onequarter: one.denominator smooth diagonals, new rounder
Zeroslash: new slash angle
    
144-25-1-GD0 RD100 SL-10
Six, Nine: improved strokes joint
M the new point structure limits the position and changes a bit
slash: improved round terminals
onequarter, onehalf, threequarters: smooth diagonals. It might not appear in the report.
F the new point structure limits the position and changes a bit
    
144-25-1-GD0 RD100
Six, Nine: improved strokes joint
fraction slash: new structure, small change
Zeroslash: new slash angle
    
144-25-1-GD100 RD0 SL-10
Bhook, Dhook distances don't match between: sharp, rounded, sharp italic, sharp rounded. 
commaaccentcomb has been corrected in 3.0
Oslash, oslash in 3.0 correction in thickness of the bar.
Six, Nine: improved strokes joint
one half, one fourth: small change in one numerator
H,L,V, M, X, W,Æ, N, D:** There are slight deviations made by the new point positioning (not fixable), but in any case improve the shapes
k, r: There is a slight deviation made by the new point positioning (not fixable), but in any case improves the shape
gravecomb: There is a slight deviation made by the new point positioning (not fixable), but in any case improves the shape.
Five.denominator: improved contours, thicker joint
    
144-25-1-GD100 RD0
Bhook and Dhook distances don't match between: sharp, rounded, sharp italic, sharp rounded. 
dollar: improved position
Oslash, oslash in 3.0 correction in thickness of the bar.
V, M, X, W, Nacute, Yacute, Ygrave: There are slight deviations made by the new point positioning, but in any case improve the shapes
tildeviet was buggy in 2.4, corrected in 3.0
hook above was missplaced in 2.4, corrected in 3.0
Six, Nine: improved strokes joint
One.denominator: thicker diagonal
braceleft: symmetric bottom and top half
guilsingleft, guillemetleft: smooth diagonals, new rounder
ampersand: smooth diagonal (new rounder), thicker bottom right curve
Five.denominator: improved contours, thicker joint
scaron is fine, no changes
Q  fixed in 3.0
    
144-25-1-GD100 RD100 SL-10
ROUNDING ADJUSTED IN THE WHOLE MASTER
commaaccentcomb has been corrected in 3.0
Oslash and oslash in 3.0 correction in thickness of the bar.
percent: same position of components as sharp
Six, Nine: improved strokes joint
Five.denominator: improved contours, thicker joint
G, C : rounding of top terminal in corrected in 3.0 
racute, rcaron have no changes
dollar: improved position
foursubscript: improved round corners and teminals, new rounder
Bhook and Dhook distances don't match between: sharp, rounded, sharp italic, sharp rounded. 
    
144-25-1-GD100 RD100
ROUNDING ADJUSTED IN THE WHOLE MASTER
Bhook and Dhook distances don't match between: sharp, rounded, sharp italic, sharp rounded. 
Oslash and oslash in 3.0 correction in thickness of the bar.
dollar: improved position
tildeviet letters were buggy in 2.4
threesubscript, threesuperscript: same position as sharp
Six, Nine: improved strokes joint
 ampersand: thicker bottom right curve and new round terminals
hookabovecomb rounding is corrected in 3.0 
abrevehookabove: hook is correctly positioned in 3.0  (Juanlu)
One.denominator: thicker diagonal
Five.denominator: improved contours, thicker joint
 braceleft: symmetric bottom and top half
 sterling: same position of shared nodes as sharp
three.denominator:  same position of shared nodes as sharp
backslash:  same position of shared nodes as sharp (Juanlu)
sacute, Ohookabove are fine. Should not be in the report  (Juan
Q  fixed in 3.0

---------

144-100-1-GD0 RD0 SL-10
Six, Nine: improved strokes joint
no changes in l (new structure)
    
144-100-1-GD0 RD0
Six, Nine: improved strokes joint
multiply: smooth diagonals, improved position of corner nodes (new structure)
    
144-100-1-GD0 RD100 SL-10
Six, Nine: improved strokes joint
    
144-100-1-GD0 RD100
Six, Nine: improved strokes joint
multiply: smooth diagonals, improved position of corner nodes (new structure)
    
144-100-1-GD100 RD0 SL-10
no changes in l, new structure
t lower curve had a wrong thickness. Corrected in v3.0
onesubscript: smooth diagonals, new rounder
x: smooth diagonals
Zeroslash: new slash angle
f: horizontal bar had a wrong thickness. Corrected in v3.0 (might not show up in the report)
    
144-100-1-GD100 RD0
t lower curve had a wrong thickness. Corrected in v3.0
f: horizontal bar had a wrong thickness. Corrected in v3.0
braceright, braceleft: symmetric top and bottom half
Zeroslash: cambio de inclinación del slash
    
144-100-1-GD100-RD100 SL-10
cent: same position as sharp
I top anchor adjusted
dollar: same position as sharp
slash: same round terminal top and bottom
    
144-100-1-GD100-RD100
t: lower curve and horizontal bar had a wrong thickness. Corrected in v3.0
braceright, braceleft: symmetric top and bottom half
Zeroslash: cambio de inclinación del slash
f: horizontal bar had a wrong thickness. Corrected in v3.0

---------

144-151-1-GD0 RD0 SL-10
Six, Nine: improved strokes joint
idotless new structure small change
jdotless stem thickness was wrong in 2.6. Corrected in 3.0
    
144-151-1-GD0 RD0
144-151-1-GD0 RD100 SL-10
Threequarters: autoalignment not activated in v2.4
jdotless stem thickness was wrong in 2.6. Corrected in 3.0
idotless stem thickness was wrong in 2.6. Corrected in 3.0
Six, Nine: improved strokes joint
 
144-151-1-GD0 RD100
no change in circumf
    
144-151-1-GD100 RD0 SL-10
Threequarters: autoalignment not activated in v2.4
Six, Nine: improved strokes joint
zeroslash: new slash angle    
    
144-151-1-GD100 RD0
braceright: symmetric top and bottom half
onesubscript: smooth diagonals, new rounder
    
144-151-1-GD100 RD100 SL-10
g has no changes
Threequarters: autoalignment not activated in v2.6
schwa did not match with sharp. Corrected in 3.0
Six, Nine: improved strokes joint
    
144-151-1-GD100 RD100
braceright: improved contours, symmetric top and bottom half


OPSZ144 WGTH 400

144-25-400-GD0 RD0 SL-10
percent: improved distribution of components (width changed!)
commaaccent adjusted
N,R, M, E slight change in 3.0 due the new point position (might disappear in the report)
Zeroslash: cambio de inclinación del slash
L has no changes in v3.0 (might disappear in the report) 
u letters are reviewed and have no changes  (might disappear in the report)
l has no changes (might disappear in the report)
Dcaron has no changes (might disappear in the report)
 
144-25-400-GD0 RD0
Onehalf, onequarter, threequarters: improved space between elements. (width changed!)
slash: smooth diagonal, corner node new rounder
l anchor corrected and centered
percent: improved distribution of components (width changed!)    
Q fixed in 3.0
braces, rounding fixed
Zeroslash: cambio de inclinación del slash
    
144-25-400-GD0-RD100 SL-10
percent: improved distribution of components (width changed!)
commaaccent corrected and adjusted
dollar: same position of shared nodes as sharp
Q fixed in 3.0    
question: same position as sharp
Zeroslash: cambio de inclinación del slash
    
- 144-25-400-GD0 RD100
dollar: same position of shared nodes as sharp
Q fixed in 3.0    
percent spacing well adjusted
braces rounding corrected
l anchor well adjusted
Onehalf, onequarter, threequarters: improved space between elements. (width changed!)
Zeroslash: new slash angle
    
144-25-400-GD100-RD0 SL-10
percent: improved distribution of components (width changed!)
commaaccent adjusted
J: corrected in 3.0 (weight of the stem)
IJ: J corrected in 3.0 (weight of the stem)
circumflex has changed due to the new point structure, might disappear
mu: thicker strokes, similar to n. This is one of the masters made by hand
W I dont see any major change in 3.0 although its reported
bracket: smooth contouts, corner node position new rounder
 Zeroslash: new slash angle
acute letters should not be in the report. Have no changes
    
144-25-400-GD100-RD0
J: corrected in 3.0 (weight of the stem)
IJ: J corrected in 3.0 (weight of the stem)
Onehalf, onequarter, threequarters: improved space between elements. (width changed!)
Zeroslash: new slash angle
percent: same width as GD0 (width changed!)
backslash: slight deviation made by the new point positioning (not fixable), but in any case improve the shape (Juanlu)
    
144-25-400-GD100-RD100 SL-10
percent: improved distribution of components (width changed!)    
commaacccent adjusted
J & IJ corrected in 3.0 (weight of the stem)
grave well adjusted   
 Zeroslash: new slash angle
    
144-25-400-GD100-RD100
J corrected in 3.0 (weight of the stem)
percent: improved distribution of components (width changed!)
braceright: smooth middle curves, new rounder
Onehalf, onequarter, threequarters: improved space between elements. (width changed!)
Zeroslash: cambio de inclinación del slash
z rounding of corners is corrected in 3.0

---------------

144-100-400-GD0 RD0 SL-10
G and diacritics: anchors centered in 3.0
 mu, micro: updated metrics, new terminal shape
l has no changes
    
144-100-400-GD0 RD0
braceright, braceleft: improved contours, symmetric top and bottom half
    
144-100-400-GD0 RD100 SL-10
 and diacritics: anchors centered in 3.0
 mu, micro: new terminal shape
    
144-100-400-GD0 RD100
braceright: improved contours, symmetric top and bottom half
    
144-100-400-GD100 RD0 SL-10
G and diacritics: anchors centered in 3.0 
ampersand: improved bottom right curve, thicker stroke
eogonek : sharp and rounded aligned in v3.0
commaaccents adjusted
Dollar has no changes
    
144-100-400-GD100 RD0
braceright, braceleft: improved contours, symmetric top and bottom half
mu: new terminal shape
eogonek matches sharp in 3.0
parenleft: symmetric top and bottom half 
    
144-100-400-GD100 RD100 SL-10
guillemets well spaced in relation to rounded
dollar: same position and thickness of vertical bar as sharp
G and diacritics: anchors centered in 3.0 
ampersand: improved bottom right curve, thicker stroke
    
144-100-400-GD100 RD100
guillemets well spaced in relation to rounded    
braceright, braceleft: improved contours, symmetric top and bottom half    
nine: thickness of round terminal matches sharp thickness

-----------

144-151-400-GD0 RD0 SL-10
comma accent adjusted    
 dollar: improved position
 Zeroslash: new slash angle

144-151-400-GD0 RD0
commaaccent adjustd
braceright: improved contours, symmetric top and bottom half
e ogonek position improved
    
144-151-400-GD0 RD100 SL-10
commaaccent position improoved
dollar: improved position
 Zeroslash: new slash angle
    
144-151-400-GD0 RD100
commaaccent better placed    
braceright: improved contours, symmetric top and bottom half
khook rounding of upper diagonal was wrong. Corrected in 3.0
    
144-151-400-GD100 RD0 SL-10    
dollar: improved position    
commaaccent adjusted
f position of horizonal bar is right in 3.0
quotedbl: scale 100% in v3.0 OK
no changes n ldot
braceright: smooth middle curves, new rounder
Zeroslash: cambio de inclinación del slash
    
144-151-400-GD100-RD0
l: bottom anchor correctly placed → Juanlu
commaaccent correctly placed in 3.0
f position of horizonal bar is right in 3.0
braceright, braceleft: improved contours, symmetric top and bottom half
quotedbl: scale 100% in v3.0 OK

144-151-400-GD100 RD100 SL-10
dollar: improved position
commaaccent letters position adjusted
quotedbl: scale 100% in v3.0 OK
f position of horizonal bar is right in 3.0
guillementright, guillementleft:** same position as sharp
cent: same position as sharp
tilde: improved in proportions and weight in 3.0
Zeroslash: new slash angle
    
144-151-400-GD100 RD100    
guillementright, guillemetleft: same position as sharp
l bottom anchor adjusted
braceright, braceleft: improved contours, symmetric top and bottom half
quotedbl: scale 100% in v3.0 OK
f position of horizonal bar is right in 3.0


OPSZ144 WGTH 1000

144-25-1000-GD0 RD0 SL-10
commaaccents adjusted
ydotbelow dot position adjusted (might dissappear)
    
144-25-1000-GD0 RD0
ydotbelow dot position adjusted (might dissappear)
    
144-25-1000-GD0 RD100 SL-10
commaaccent adjusted
ydotbelow dot position adjusted (might dissappear)
    
144-25-1000-GD0 RD100
ydotbelow dot position adjusted (might dissappear)
r accents adjusted
    
144-25-1000-GD100 RD0 SL-10
commaaccents adjusted
ydotbelow dot position adjusted (might dissappear)    
    
144-25-1000-GD100 RD0
ycircuflex has no changes
ydotbelow dot position adjusted (might dissappear)
    
144-25-1000-GD100 RD100 SL-10
commaaccents adjusted
r accents readjusted
ydotbelow dot position adjusted (might dissappear)
        
144-25-1000-GD100 RD100
r design readjusted
raccents readjusted
ydotbelow dot position adjusted (might dissappear)

---------

144-100-1000-GD0 RD0 SL-10
mu, micro: new terminal shape
ydotbelow dot position adjusted (might dissappear)
    
144-100-1000-GD0 RD0
commaaccent letters relocated
braceleft and right, rounding adjusted
ydotbelow dot position adjusted (might dissappear)

144-100-1000-GD0 RD100 SL-10
ydotbelow dot position adjusted (might dissappear)
 
144-100-1000-GD0 RD100
commaaccent letters reajustd
 j rounding at the top waswrong in 2.4. Corrected in 3.0. May disappear for other adjustments
 braceleft: smooth middle curves, new rounder
ydotbelow dot position adjusted (might dissappear)
    
144-100-1000-GD100 RD0 SL-10
 mu: new terminal shape
ydotbelow dot position adjusted (might dissappear)
    
144-100-1000-GD100 RD0
commaaccent adjusted
braceleft and right, rounding adjusted
ydotbelow dot position adjusted (might dissappear)
     
144-100-1000-GD100 RD100 SL-10
ydotbelow dot position adjusted (might dissappear)

144-100-1000-GD100 RD100
j rounding at the top waswrong in 2.4. Corrected in 3.0. May disappear for other adjustments
adjustment in all commaaccent letters
braceleft: smooth middle curves, new rounder
ydotbelow dot position adjusted (might dissappear)
    
    
---------

144-151-1000-GD0 RD0 SL-10
v: better position, more to the center
y and yhook: same position as v
    
144-151-1000-GD0 RD0
144-151-1000-GD0 RD100 SL-10
threequartes, onehalf, onequarter: autoalignment activated in v3.0 (no changes in width)
x has no changes
question: new rounder for better interpolation
yhook: new design more consistent with sharp
     
144-151-1000-GD0 RD100
yhook: new design more consistent with sharp
ydotbelow: position of anchor for dot is corrected in v3.0
    
144-151-1000-GD100 RD0 SL-10
threequartes, onehalf, onequarter: autoalignment activated in v3.0 (no changes in width)
v: better position, more to the center
y and yhook: same position as v
    
144-151-1000-GD100 RD0
144-151-1000-GD100 RD100 SL-10
threequartes, onehalf, onequarter: autoalignment activated in v3.0 (no changes in width)
yhook: new design more consistent with sharp
question: new rounder for better interpolation
        
144-151-1000-GD100-RD100
yhook: new design more consistent with sharp

**Comment by MariannaPaszkowska** [comment]
Many thanks! Will review that for the latest import.

**Comment by MariannaPaszkowska** [comment]
#1102
