### ISSUE TITLE
Update the shaping expectations

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#1114]
We are failing shaping FB tests in the release workflow: https://github.com/googlefonts/googlesans-flex/actions/runs/12373571481/job/34534789121#step:6:668

The changes were intentional, it's the Aring aring updates we did. #1098 
https://github.com/googlefonts/googlesans-flex/pull/1098

**Comment by RickyDaMa** [comment]
I believe this will have been caused by us not updating the shaping expectations for the Android fonts when adding/updating the shaping tests for ccmp in #1098. A simple fix at least, but explains why this wasn't found until a release was attempted - ordinary builds don't produce the Android adjusted fonts (or test them)
