### ISSUE TITLE
Confirm Width axis min and max values

### ISSUE THREAD

**Issue by davelab6** [googlefonts/googlesans-flex#114]
>> @tiroj Can someone explain why this is designated ‘wdth 25’?
>
> @dberlow At Google’s request, we use the width of opsz 144. The initial opsz144, wdth25, wght100 design was made about 1/4 the width of the opsz wdth100 wght100.Then it was determined that that was not condensed enough, but the value was left the same.

_– Originally posted in https://github.com/googlefonts/googlesans-flex/issues/100#issuecomment-1353336910_

I vaguely recall that, to establish the non-opsz-aware wdth axis min and max values, since it is meaningful to end-users to quickly know how far the range can go in the extreme case, when comparing the family against other families before even downloading them, then I requested measuring the actual (UPM) width of a reference character (I think `H` or `space`?) at the wdth-min opsz-max designspace location, and measuring the actual width of the wdth-default opsz-max designspace location, and calculating the former as a percentage of the latter (and repeating for wdth-max).

Ideally there will be a Font Bakery check to carry out these measurements and check the fvar min/max values and WARN if they are not as the check expects.

> but the value was left the same

That seems like a mistake :) Let's make the values accurate to the largest opsz

**Comment by tiroj** [comment]
Do you have a spec for how you want the wdth axis to function across the wght and opsz axes? You need to have agreement on what you want the wdth axis to do, because the nominal width value at best approximates the actual horizontal compression or expansion of the length of a string of text depending on a) what characters that text contains and b) how the design can be expressed at that nominal width given the impact of stroke weight. The latter is important, because obviously a thin weight is able to be proportionally much more tightly compressed than a black weight. So if you define the wdth scale relative to the thin weight, you can easily have something that is 25% compressed relative to its normal width, but as weight increases your nominal width gets further and further away from your actual width compression, which seems to be the case with the GS Flex wdth scale.

That may be intentional, i.e. you may have good reasons why you want the wdth scale to be defined in terms of the lightest wght master. It surprised me because I am more used to seeing the wdth scale defined relative to the wght 400 ‘Regular’ design, on the basis that this a) is going to be the more frequently used weight region, b) is what users tend to think of as the ‘default’ instance of a font (regardless of whether it is the default instance in the OTvar technical sense), and c) means that the approximation to actual width across the wght and opsz axes diverges in two directions instead of one, meaning that the divergence at the extremes is less pronounced than if only at one extreme.

**Comment by tiroj** [comment]
By way of illustration, this screenshot from https://github.com/googlefonts/googlesans-flex/issues/96 shows two glyphs from the opsz 144 wdth 25 wght 1000 design, which I am reasonably sure are a _long_ way from approximating 25% the width of the  opsz 144 wdth 100 wght 1000 design.
<img width="393" alt="image" src="https://user-images.githubusercontent.com/5614500/207939806-876ec6cc-33bb-40e5-ab04-e2644d89368a.png">

**Comment by dberlow** [comment]
…and as a result, not a long way from the wght of the rest of 1000’s widths:)On Dec 15, 2022, at 1:34 PM, John Hudson ***@***.***> wrote:﻿
By way of illustration, this screenshot from #96 shows two glyphs from the opsz 144 wdth 25 wght 1000 design, which I am reasonably sure are a long way from approximating 25% the width of the  opsz 144 wdth 100 wght 1000 design.

**Comment by tiroj** [comment]
Important note: https://github.com/googlefonts/googlesans-flex/issues/100#issuecomment-1353542066

Still pondering that **wght 25** value.

**Comment by MariannaPaszkowska** [comment]
related #784

**Comment by MariannaPaszkowska** [comment]
@simoncozens Dave mentions a potential FB check of the width changes along the wdth axis here (see the very top). I thought this might be interesting to you.

**Comment by MariannaPaszkowska** [comment]
@octaviopardo I am closing it as we made adjustments to the wdth 25 following this discussion.
