### ISSUE TITLE
gasp table for wght 1 rendering

### ISSUE THREAD

**Issue by davelab6** [googlefonts/googlesans-flex#115]
In https://github.com/googlefonts/googlesans-flex/issues/103 @MariannaPaszkowska posted about how opsz 144 wght 1 rendering in Chrome can break up below a certain font-size. Today on a call @dberlow suggest the `gasp` table could help resolve this. Marianna said she's familiar with setting the table values, so assigning to her to experiment with this

**Comment by belluzj** [comment]
As proposed in our meeting @MariannaPaszkowska we did some testing and we think it's a Chrome rendering bug, as it's not possible to reproduce in Safari and Firefox. It happens both on mac and Windows at big enough sizes and also isn't specific to Google Sans Flex, we reproduced the same rendering issues with the static font Fira Sans Two (from https://bboxtype.com/typefaces/FiraSans/#!layout=specimen, which we could use to open a public bug report without mentioning Google Sans, if needed).

The macs on which we tested didn't have Retina screens so we had to go higher in font size (around 300px) to trigger the bug in Chrome but it did show eventually. Safari and Firefox look fine at the same size.

In terms of gasp and prep, we tested the following:
* changing the gasp to Smooth greyscale-only over 72 and Do nothing over 72
  * both options did not fix the issue, the only visible difference was on Windows where "do nothing" made the font pixelated (as expected from turning off smoothing).
* ensuring that the prep [SCANCTRL[ ]](https://learn.microsoft.com/en-us/typography/opentype/spec/tt_instructions#scan-conversion-control) was enabling dropout control for all sizes (0x01FF = Always do dropout control)
  * it was already the case; nothing more we can do
* testing different values for the prep [SCANTYPE[ ]](https://learn.microsoft.com/en-us/typography/opentype/spec/tt_instructions#scantype): 0, 4, 5 (original value = 5)
* delete the prep table altogether
* instantiate the variable font and look at the static instance instead (in case it was a VF-related bug)
* add our default VTT template to the font (without hinting any glyph, just to add a cvt table etc)
  * none of the above made a difference

Which leads us to believe it's a Chrome bug rather than a font bug.

Also, from testing with Fira Sans Two, it happens in a similar way with the TTF and OTF.

**Comment by MariannaPaszkowska** [comment]
@belluzj do you recall if this was reported?

**Comment by MariannaPaszkowska** [comment]
Related: #103

**Comment by belluzj** [comment]
I'm looking for a bug report and if we haven't we could certainly open one.

**Comment by belluzj** [comment]
We didn't create an official bug report for this issue. However, there are the following reports:

- in the Google chat, Nikolaus talked to Dominik about the same issue that we spotted on our library font Neumond, which has super-thin hairlines

![image](https://github.com/googlefonts/googlesans-flex/assets/3616772/1e1ae328-8cc6-4756-9754-1533aeba30df)
![image](https://github.com/googlefonts/googlesans-flex/assets/3616772/b21911a4-0094-40d7-a1bb-658fc87f889c)
![image](https://github.com/googlefonts/googlesans-flex/assets/3616772/debb8df8-cf62-4a5e-92e0-645c9d9a174e)
![image](https://github.com/googlefonts/googlesans-flex/assets/3616772/00bb0637-cfb4-4322-9492-c050e69501c0)


- There is this bug report which is similar (in that it highlights the shortcomings of the SDF rendering): https://bugs.chromium.org/p/chromium/issues/detail?id=1030780

If that's OK, I think we should add message to that existing bug report to point out the issues with Fira Sans Two and our font Neumond, which we're fine to use an example, as it's visible on our public website.

What do you think? Good for us to write that?

In case you have more leverage from inside Google, you may also be able to report the issue privately, with the added weight that it concerns your brand font.
