### ISSUE TITLE
Font Gardener migration

### ISSUE THREAD

**Issue by RickyDaMa** [googlefonts/googlesans-flex#25]
[Font Gardener](https://github.com/daltonmaag/Fontgardener) is a prototype application written by @madig to convert UFOs into an alternative format - the Font Garden. Its primary aims are reducing data duplication and making diffs easier to understand / reason with (especially on large repositories).

What this means for the Google Sans Flex repo is that instead of storing UFO sources, we’d store Font Garden sources. This is a significant change for every workflow in place, as the UFOs/Glyphs files that designers provide will need to be converted to UFO, and then the font garden(s) will need to be converted back to UFOs for compilation (until `fontmake` natively supports font gardens as input format, should font gardens be widely adopted). From a build time standpoint, it will add a step to the compilation process, but we’re hoping this won’t be too impactful, as the tool is being written in Rust.

Motivations:
- Human understandable Git diffs with per-script and per-glyph folders + CSV files for diffing glyph data in one place

What needs to be done:
- Implement kerning handling in Font Gardener
- Ensure we’re storing glyphs -> layers instead of layers -> glyphs
- Build pipeline and CI support for font gardens
- Implement scripts for importing work of FDs and/or facilitating FDs in using the new tool

**Comment by dberlow** [comment]
Is this application and format opensource?

On Nov 7, 2022, at 9:34 AM, Ricky ***@***.***> wrote:

﻿
Font Gardener is a prototype application written by @madig to convert UFOs into an alternative format - the Font Garden. Its primary aims are reducing data duplication and making diffs easier to understand / reason with (especially on large repositories).

What this means for the Google Sans Flex repo is that instead of storing UFO sources, we’d store Font Garden sources. This is a significant change for every workflow in place, as the UFOs/Glyphs files that designers provide will need to be converted to UFO, and then the font garden(s) will need to be converted back to UFOs for compilation (until fontmake natively supports font gardens as input format, should font gardens be widely adopted). From a build time standpoint, it will add a step to the compilation process, but we’re hoping this won’t be too impactful, as the tool is being written in Rust.

Motivations:

Human understandable Git diffs with per-script and per-glyph folders + CSV files for diffing glyph data in one place
What needs to be done:

Implement kerning handling in Font Gardener
Ensure we’re storing glyphs -> layers instead of layers -> glyphs
Build pipeline and CI support for font gardens
Implement scripts for importing work of FDs and/or facilitating FDs in using the new tool

**Comment by madig** [comment]
Yes, you can find it at https://github.com/daltonmaag/Fontgardener/. It's currently a proof of concept more than anything usable.

**Comment by dberlow** [comment]
This looks interesting, but we have 6 weeks left. And also I’m not sure of the value of using anything but .ttfs as the benchmark format to test against other ttfs to find the differences in tt tables that result in visual or other notable differences.

Let us know what we can do to help.



On Nov 7, 2022, at 1:57 PM, Nikolaus Waxweiler ***@***.***> wrote:

﻿
Yes, you can find it at https://github.com/daltonmaag/Fontgardener/. It's currently a proof of concept more than anything usable.

**Comment by madig** [comment]
We likely won't use it initially, but may switch to it over time after more development.

**Comment by RickyDaMa** [comment]
Yeah as Nik said - for the initial release we're not going to pursue FontGardener - it needs more work. It's more of a mid-long term maintainability consideration if we can get it production ready. We're expecting to pick back up engineering work on it later this year or early next year IIRC

**Comment by MariannaPaszkowska** [comment]
won't do for now, we will keep working on a new, better format.
