### ISSUE TITLE
Create tool for checking the MVAR table

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#250]

**Comment by madig** [comment]
Hm, what would you like to check? See the tag list in https://learn.microsoft.com/en-us/typography/opentype/spec/mvar#value-tags.

I'll copy over various values from GS and then you just need to look at the rest. PR coming soon.

**Comment by MariannaPaszkowska** [comment]
This is still a backlog issue with low priority.

Here is a list of my ideas. let me know what you think of them:

- [ ] Should not vary:

'hasc'	horizontal ascender	OS/2.sTypoAscender
'hdsc'	horizontal descender	OS/2.sTypoDescender
'stro'	strikeout offset	OS/2.yStrikeoutPosition
'strs'	strikeout size	OS/2.yStrikeoutSize 
'undo'	underline offset	post.underlinePosition
'unds'	underline size	post.underlineThickness

- [ ] Only vary if an italic axis is present and only on the italic axis:

'hcrs'	horizontal caret rise	hhea.caretSlopeRise

- [ ] Should follow x height

'xhgt'	x height	OS/2.sxHeight

- [ ] Should follow the positioning of the subscript and superscript:

'sbxs'	subscript em x size	OS/2.ySubscriptXSize
'sbyo'	subscript em y offset	OS/2.ySubscriptYOffset
'spxs'	superscript em x size	OS/2.ySuperscriptXSize
'spys'	superscript em y size	OS/2.ySuperscriptYSize

In our case, those values shouldn't change as we vary along the ROND axis.

**Comment by MariannaPaszkowska** [comment]
Test case: #246

**Comment by dberlow** [comment]
I am interested in discussing a few of these values in our meeting today

**Comment by dberlow** [comment]
I dicussed these values with Chris.
'hasc' horizontal ascender OS/2.sTypoAscender
'hdsc' horizontal descender OS/2.sTypoDescender
...are different in ROND100 because of overshoots, I think, and should remain the same values as ROND0.
I don't think this is any different than ignoring the overshoot of /O uppercase.

This,
'stro' strikeout offset OS/2.yStrikeoutPosition
'strs' strikeout size OS/2.yStrikeoutSize
and the one below, 
'undo' underline offset post.underlinePosition
'unds' underline size post.underlineThickness
I think the values related to wght need to be tied to a glyph, like em dash, and to vary with the designspace in weight.

The location of strikethrough and underline should probably be consistent though out, but I'm not sure how to keep heavier underlines from obscuring descenders,
