### ISSUE TITLE
Port Harfbuzz test suite from Google Sans / Font Bakery

### ISSUE THREAD

**Issue by RickyDaMa** [googlefonts/googlesans-flex#29]
It's complementary to diffenator2 (#26), more specific, and far quicker

**Comment by madig** [comment]
There are two ways to go here:

1. Reuse the code from Google Sans and improve it a bit (e.g. more ergonomic snapshot updates)
2. Use fontbakery's shaping testing, which is point 1 ported to fontbakery and improve it some more (e.g. snapshot updating tool).

Reusing and improving a bit is quicker, switching over to fontbakery needs some additonal work:

- I don't know how battle tested it is
- There is no snapshot updating tool, so we'd want to write one
- I am tempted to extract the core logic into a standalone library where adding a management tool on top would be easy, because I think fontbakery is the wrong place for it. This would require negotiations with fontbakery.

**Comment by RickyDaMa** [comment]
Delayed until next quarter on the basis that there's not going to be a stable base to regression test against until the first release.

Could still test against Google Sans, just not Google Sans Flex

**Comment by belluzj** [comment]
Use the Google Sans one for now.

Check what the status is of the Fontbakery version, and check how difficult it would be to switch to the Fontbakery one in a year for example.

**Comment by madig** [comment]
I imported the GS version in https://github.com/googlefonts/googlesans-flex/pull/45. Needs to be filled in properly close to release.

**Comment by MariannaPaszkowska** [comment]
related #762

**Comment by Hoolean** [comment]
Discussed in meeting: we may be able to cover some of this functionality with custom diffenator2 wordlists and by upstreaming shaping checks to Shaperglot/Hyperglot
