### ISSUE TITLE
Actions: Incorrect font path issue, proofs are not building

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#32]
https://github.com/googlefonts/googlesans-flex/actions/runs/3424547501/jobs/5704342870#step:12:20

**Comment by RickyDaMa** [comment]
Hi Marianna!

Thanks for raising this! The problem is caused by the fact that currently the Designspace is configured such that only VFs are produced during the build process. On the `fb-wip` branch, proofs (and fontbakery checks) were being done against static TTFs, as the branch was created before my changes (to make both run against VFs) landed in `main`. There were no static TTFs to test against, thus CI fails.

I have cherry-picked two commits across, and pushed that to `fb-wip`. These update the CI to work against the VFs.

You shouldn't have any issues with builds now - it works locally for me 😄

**Comment by MariannaPaszkowska** [comment]
That's great! Thank you, @RickyDaMa!
CC @chrissimpkins @sannorozco
