### ISSUE TITLE
aogonek.alt interpolation bug

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#380]
<img width="1273" alt="Screenshot 2023-02-15 at 7 37 18 PM" src="https://user-images.githubusercontent.com/22956348/219115240-ede73b63-ce2d-4e65-b786-bfc28693d07b.png">

<img width="934" alt="Screenshot 2023-02-16 at 3 24 51 PM" src="https://user-images.githubusercontent.com/22956348/219376814-92bca9f6-3d59-4184-bf65-e17d19905cf6.png">

**Comment by ghost** [comment]
Same string and values proofed
Already fixed in yesterday's commit
 
<img width="1792" alt="Rond0" src="https://user-images.githubusercontent.com/78229912/219815014-d4cbfeed-7d42-4c05-af07-87a6a93181d9.png">
<img width="1788" alt="Rond100" src="https://user-images.githubusercontent.com/78229912/219815029-1f73d742-d97c-4d0a-8251-c6777ed432c4.png">
