### ISSUE TITLE
ROND axis GRAD axis reflow 

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#397]
- [x] The following glyphs have variation in horizontal                     
          advance due to the **ROND** axis: 
e, edieresis, ecircumflex, edotaccent,  
emacron, ecaron, eacute, egrave and eogonek

Please check the advanced widths of "e" in wght 1, wdth 151, and size 6 ROND=0 vs ROND =100

- [x] Please check the "wiggle.medium" glyph - masters from sharp need to be copied to round.

- [x] The following glyphs have variation in horizontal                     
          advance due to the **GRAD** axis: 
quotesinglbase, quoteleft, quotedblbase,
ldot, quoteright, quotedblright and quotedblleft 

Please check the advanced widths of "ŀ" and "quotesinglbase, quoteleft, quotedblbase, quoteright, quotedblright and quotedblleft "
in wght 1, wdth 25-155, and size 144 GRAD=0 vs GRAD =100

Please update the sources.

**Comment by dberlow** [comment]
If I understand:
variation in horizontal advance due to the GRAD axis: quotesinglbase, quoteleft, quotedblbase,
ldot, quoteright, quotedblright and quotedblleft

opsz18, wdth100, wght400, ROND0, GRAD0
opsz18, wdth100, wght400, ROND0, GRAD-50
and
opsz18, wdth100, wght400, ROND0, GRAD50

...all have identical widths. 

opsz18, wdth100, wght400, ROND0, GRAD0
and
opsz18, wdth100, wght400, ROND0, GRAD100
e, edieresis, ecircumflex, edotaccent,
emacron, ecaron, eacute, egrave and eogonek

...have identical widths as shown below in the following order;
opsz18, wdth100, wght400, ROND0, GRAD100
opsz18, wdth100, wght400, ROND0, GRAD-50
opsz18, wdth100, wght400, ROND0, GRAD0
opsz18, wdth100, wght400, ROND0, GRAD50

<img width="722" alt="image" src="https://user-images.githubusercontent.com/1956494/220106719-7ac90452-b1b3-4d8f-933d-de2f9e393dbc.png">

**Comment by dberlow** [comment]
/ldot missed in review, if I understand the issue correctly, it is correct too. 
<img width="353" alt="Screen Shot 2023-02-20 at 7 38 58 AM" src="https://user-images.githubusercontent.com/1956494/220110561-c20e1f3e-c30a-448f-b1b1-d10d953c67fa.png">

**Comment by MariannaPaszkowska** [comment]
In the latest build also wiggle.medium has reflow issues:

https://github.com/googlefonts/googlesans-flex/actions/runs/4223491855

<img width="1333" alt="Screenshot 2023-02-20 at 3 18 25 PM" src="https://user-images.githubusercontent.com/22956348/220119671-23aa243b-3cf4-4fed-b8e4-9cd19852a664.png">

**Comment by MariannaPaszkowska** [comment]
@dberlow Please check advanced widths of "e" in wght 1, wdth 151, and size 6 ROND=0 vs ROND =100

(I'm investigating other reported issues more, to give you more precise feedback)

**Comment by dberlow** [comment]
corrections commmited

**Comment by MariannaPaszkowska** [comment]
@dberlow I think I found the other one: please check the advanced widths of "ŀ" and "quotesinglbase, quoteleft, quotedblbase, quoteright, quotedblright and quotedblleft "
in wght 1, wdth 25-155, and size 144 GRAD=0 vs. GRAD =100

**Comment by MariannaPaszkowska** [comment]
Please check the "wiggle.medium" glyph - masters from sharp need to be copied to round.

**Comment by dberlow** [comment]
got it, thanks.

**Comment by dberlow** [comment]
The wiggle waits for a mass copy from sharp or a sparsing of the round
masters for all wiggle glyphs.
