### ISSUE TITLE
Build fails because of the rvrn feature 

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#405]
Build fails because there are rvrn glyphs referenced in the code: Q.rvrn, Oslash.rvrn, oslash.rvrn, while we're not importing them. 
We have decided not to use the rvrn feature and use sparse intermediate masters instead. I prefer to avoid introducing rvrn feature. @sannorozco, please explain. 
That's the commit that introduced those changes: [6c080f8](https://github.com/googlefonts/googlesans-flex/commit/6c080f8395f6889790f3a941805a5243184ba8f6) 

- [x] remove rvrn statements from the designspace
- add intermediete masters for Q, tracked in #325 
- [x] leave Oslash oslash without rvrn and intermediate masters for this release.

CC @chrissimpkins

**Comment by dberlow** [comment]
Santiago Told me about this yesterday afternoon, he feels that this is the only effective way to deal with these glyphs without adding many intermediates

**Comment by chrissimpkins** [comment]
Is `Q` used in any chained substitutions?

**Comment by chrissimpkins** [comment]
Or is any other glyph that relies on these Oslash / oslash forms used in chained substitutions?

**Comment by MariannaPaszkowska** [comment]
Q, Oslash and oslash are not currently used in features. 
We also have the dollar and cent that have the broken bar issues and potentially need this treatment. Those are referenced in the tabular figures feature (tnum, lnum).

**Comment by chrissimpkins** [comment]
Let's provide a full summary of the extent of the problem (what glyphs are involved, what other features are involved on those glyphs, where in the design space are we attempting to perform the rvrn style substitution), understand if it is not possible to support it beyond use of a rvrn/rclt feature, and we will reach a decision on how to address it.

**Comment by MariannaPaszkowska** [comment]
It was decided during the meeting yesterday that we won't be introducing the rvrn feature. 
We will:

- remove rvrn statements from the designspace
- add intermediete masters for Q; tracked in Fix tail of the Q  #325
- leave Oslash, oslash without rvrn and intermediate masters for this release.

**Comment by tiroj** [comment]
Is there an issue or other reference that explains the reasoning behind avoiding rvrn? — I can imagine some possible reasons, but am interested to know what your thinking has been.

**Comment by chrissimpkins** [comment]
> Is there an issue or other reference that explains the reasoning behind avoiding rvrn? — I can imagine some possible reasons, but am interested to know what your thinking has been.

We ran into problems with glyphs that were defined with both rvrn and chained substitutions in the Google Sans project.  This was due to the always-first rvrn sub order in these substitution chains.  This applied to glyphs like `G` and `y` that have undesirable interpolation styles across the optical size axis.  As I recall, we ended up losing our smcp substitutions following the rvrn substitution.  We looked into mapping the full sequence of required glyphs to follow the substitution pattern, but it wound up being *easier* (well, easier for everyone but the type designer I suppose!) to turn them into interpolatable forms and "hide" the interpolation (with a sharp 0.001 unit avar1 bend on the opsz 17-18 range in GS, with a master positioned 0.001 unit away from the next master in this project that has a full 6pt - 144pt opsz range).

**Comment by tiroj** [comment]
> As I recall, we ended up losing our smcp substitutions following the rvrn substitution.

Couldn’t that be fairly simply resolved by including all the rvrn forms as inputs in the smcp lookup?

**Comment by MariannaPaszkowska** [comment]
We considered putting them into the 'rlig' feature, but AFAIK this isn't supported in Adobe products (I haven't tested that recently, though).

**Comment by tiroj** [comment]
I’m thinking in terms of simply taking the output of the rvrn lookup and mapping them all as inputs in any features for which their variation space shapes are irrelevant, so e.g. your c2sc smallcap lookup would include something like

```
   ...
   sub Q by Q.sc;
   sub Q.rvrn by Q.sc;
   ...
   sub Oslash by Oslash.sc;
   sub Oslash.rvrn -> Oslash.sc;
   ...
```

**Comment by chrissimpkins** [comment]
Yes, I think that this is very possible.  The complications came as we got into chains of 3+ subs in Google Sans.

**Comment by tiroj** [comment]
Not by way of trying to persuade anyone to use a different method than the intermediate master approach you’ve decided on, but I would be interested to think through the possible GSUB-only solutions if you have a list of the affected glyphs and their layout behaviours.

**Comment by dberlow** [comment]
As far as I know, the glyphs affected are:Proportional monetary symbols, and their tabular partners to hinder rvrn use.  In these glyphs we want to split a bar that runs through a counter, and join a bar that no longer needs to split. In the process, the base glyph needs to change so that the color is retained. When the bar splits, the glyph gets heavier, when it joins, the glyph gets lighter. The splits and joins form a pattern through the designspace where width and weight dictate the decision.Alphabetic glyphs, upper and lowercase O-slash, with the same issue, but with a future of a small cap feature to hinder rvrn.Unless Chris or Santiago have any other glyphs to add…On Feb 23, 2023, at 5:58 PM, John Hudson ***@***.***> wrote:﻿
Not by way of trying to persuade anyone to use a different method than the intermediate master approach you’ve decided on, but I would be interested to think through the possible GSUB-only solutions if you have a list of the affected glyphs and their layout behaviours.

**Comment by tiroj** [comment]
> The splits and joins form a pattern through the designspace where width and weight dictate the decision.

Do the splits and joins happen for all affected glyphs at the same width and weight locations, i.e. would FeatureVariations for the splt bar in a proportional and tabular $ apply to the same range of the relevant axes? Would the treatment of /Oslash be the same for smallcap /Oslash.sc in the same range?

Or is it more complex than that in terms of wanting to trigger variant forms of numerals or smallcaps in different locations in the design space?

**Comment by dberlow** [comment]
﻿Thanks John,‘Do the splits and joins happen for all affected glyphs at the same width and weight locations, i.e. would FeatureVariations for the splt bar in a proportional and tabular $ apply to the same range of the relevant axes?’There are, I think, three stresses on the issue. One is a design consideration for the reader, to keep the glyphs that need to split at the same instance splitting together. E.g. we generally want upper and lowercase o-bars to match, I think. Second is a consideration of opsz, and what’s best for legibility at a given size. That may override the first point. And third is the location in the wght and wdth.In general, I need to document some things in the OT spec that were well-imagined for instances, but not for variables, and some other things.I’m starting to collect that for comments here; https://docs.google.com/document/d/1-W5EELtbbCuTI4hc4HU4eLQDsKB5jN4eis0oeKn-Vo4/editRvrn mapping fits into that list, though I need to look at the pattern relative to the stresses and figure out how it’d be described in words and stored in fonts.When I return to my studio, the task of illustrations begins.Let me know with comments there as the doc goes along, thanks.Sign-indocs.google.comOn Feb 23, 2023, at 8:27 PM, John Hudson ***@***.***> wrote:﻿

The splits and joins form a pattern through the designspace where width and weight dictate the decision.

Do the splits and joins happen for all affected glyphs at the same width and weight locations, i.e. would FeatureVariations for the splt bar in a proportional and tabular $ apply to the same range of the relevant axes? Would the treatment of /Oslash be the same for smallcap /Oslash.sc in the same range?
Or is it more complex than that in terms of wanting to trigger variant forms of numerals or smallcaps in different locations in the design space?

**Comment by tiroj** [comment]
Thanks for the additional insights.

> One is a design consideration for the reader, to keep the glyphs that need to split at the same instance splitting together. E.g. we generally want upper and lowercase o-bars to match, I think.

Agreed, and that does at least slightly simplify the problem in that it suggests these variants should ideally be triggered in a common region of the design space, which in turn suggests that they _could_ be handled via rvrn and then passed to downstream tnum, smcp, etc. lookups, e.g.

```
   sub oslash by oslash.sc;
   sub oslash.rvrn by oslash.rvrn.sc;
```
In that respect, they would operate exactly like locl variant glyphs, being primary replacements for cmap output prior to other GSUB.

_____

I’ll take a look at your doc.

A thought I have is to try to come up with an if-then model for font makers to follow when considering how to solve this kind of problem, to help discern when rvrn is an appropriate solution and when it isn’t.

**Comment by dberlow** [comment]
The other thing related to this of interest to me, is whether the behavior of the ital “axis” has any issues with subsequent substitutions. It is, in essence, a grouped rvrn-like substitution triggered by selection of the design space location ital1.On Feb 24, 2023, at 11:18 AM, John Hudson ***@***.***> wrote:﻿
Thanks for the additional insights.

One is a design consideration for the reader, to keep the glyphs that need to split at the same instance splitting together. E.g. we generally want upper and lowercase o-bars to match, I think.

Agreed, and that does at least slightly simplify the problem in that it suggests these variants should ideally be triggered in a common region of the design space, which in turn suggests that they could be handled via rvrn and then passed to downstream tnum, smcp, etc. lookups, e.g.
   sub oslash by oslash.sc
   sub oslash.rvrn by oslash.rvrn.sc

In that respect, they would operate exactly like locl variant glyphs, being primary replacements for cmap output prior to other GSUB.

I’ll take a look at your doc.
A thought I have is to try to come up with an if-then model for font makers to follow when considering how to solve this kind of problem, to help discern when rvrn is an appropriate solution and when it isn’t.

**Comment by tiroj** [comment]
Oh, I’m of the opinion that the ital axis is a silly thing and should almost always be avoided. Unless one is actually going to make a design that interpolates _between_ roman and italic forms, there is no good reason to put roman and italic in the same variable font. The ital axis only exists because of an architecture preference that Microsoft had for the STAT table.

**Comment by dberlow** [comment]
Oh, but ital does not interpolate. According to the spec, it has two and only two values, 0 is Roman, 1 is italic. That’s why I put axis in quotes. Ital only does a glyph swap. So I’m almost curious if any feature substitution can happen before of after that if rvrn, which does nothing more, but is screwed up.On Feb 25, 2023, at 10:53 AM, John Hudson ***@***.***> wrote:﻿
Oh, I’m of the opinion that the ital axis is a silly thing and should almost always be avoided. Unless one is actually going to make a design that interpolates between roman and italic forms, there is no good reason to put roman and italic in the same variable font. The ital axis only exists because of an architecture preference that Microsoft had for the STAT table.

**Comment by tiroj** [comment]
> Oh, but ital does not interpolate. According to the spec, it has two and only two values, 0 is Roman, 1 is italic. That’s why I put axis in quotes. Ital only does a glyph swap. So I’m almost curious if any feature substitution can happen before of after that if rvrn, which does nothing more, but is screwed up.

I’ve not tested this, since I never put italics in the same font as the roman, but what _should_ happen is that any variation selection happens first, and that would include selection of 0 or 1 on the ital axis. Instantiation of a variation is equivalent to font selection—indeed, I think Apple for one treats it as identical to font selection—, so that happens first and then OTL happens. So no GSUB happens before the ital axis selection, and after that rvrn would apply to the output of that selection.

**Comment by dberlow** [comment]
The thing im pointing to, is that invoking the ital axis Is a 1 for 1 glyph substitution of the Roman for the italic form. And using features, like the 1 for 1 substitution of an italic finial works afterwards. 

Thus, in and of themselves regardless of the order of, or why of things that are done, rvrn is a glyph substitution too. And one glyph substitution should be any another glyph substitution And allow feature-based substitutions to occur after them.

It seems to us like arbitrary BS that we can’t do the best we can do because the format is simply inconsistent.

**Comment by tiroj** [comment]
> The thing im pointing to, is that invoking the ital axis Is a 1 for 1 glyph substitution of the Roman for the italic form.

Let’s step back a moment and ask how the ital axis is implemented in the font. While the ital axis functions as a 1-for-1 substitution of glyph forms, that doesn’t imply that it is a GSUB operation, which was my point about it being something that happens prior to GSUB. But then I realised that one _could_ implement ital axis support using rvrn itself, i.e. having the same set of roman outlines at both extremes of the ital axis and using FeatureVariations in an rvrn lookup to substitute the italic glyphs when the axis setting =1.

So how is the ital axis implemented in GSF?

> > Thus, in and of themselves regardless of the order of, or why of things that are done, rvrn is a glyph substitution too. And one glyph substitution should be any another glyph substitution And allow feature-based substitutions to occur after them.
> 
> It seems to us like arbitrary BS that we can’t do the best we can do because the format is simply inconsistent.

FeatureVariations can be applied to _any_ GSUB feature. The rvrn feature is simply a special case of a feature that shaping engines will apply early in OTL processing, like ccmp or locl, in what I classify as ‘Default glyph pre-processing’. That is its only reason for existing. I think the problem you may be encountering, if I am understanding Marianna’s comments correctly, is actually inconsistency in support for other OTL features in some shaping engines, such that you can’t find a reliably supported downstream feature in which to locate required FeatureVariation substitutions that you want to be processed later. That is indeed ‘arbitrary BS’, but it is in the implementation not in the format.

**Comment by dberlow** [comment]
We are using slnt.

**Comment by dberlow** [comment]
Corrected myself, we used slnt in Roboto,. GSF Is contour compatible so the decision can be made later whether to have a separate italic font, use ital or use slnt.
