### ISSUE TITLE
Update vertical metrics in the sources to match Google Sans v10

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#46]
We want to update vertical metrics in the GS Flex sources to match Google Sans v10.

Let us know if there is a strong design rationale against keeping vertical metrics incompatible with Google Sans v10. The adoption process will be more difficult for our teams if they need to be incompatible. 

Objectives: 
1. we want cross-platform line spacing consistency; 
2. we want to avoid linespacing regressions vs. Google Sans.

Values from GS v10:
hhea:
```
   ascent value="966"
   descent value="-286"
   lineGap value="0"
```

OS/2:
```
    sTypoAscender value="966"
    sTypoDescender value="-286"
    sTypoLineGap value="0"

```
Please note: In OS/2. table, the fsSelection bit 7 'Use Typo Metrics' should be on.
We need to scale those values to 2000UPM

It would be great to PR this into Font Bureau's sources next week so everyone can review fonts with the proper set of v metrics.

EDIT:
We should keep Subscript and Superscript values consistent too.  
```
    ySubscriptXSize value
    ySubscriptYSize value
    ySubscriptXOffset value
    ySubscriptYOffset value
    
    ySuperscriptXSize value
    ySuperscriptYSize value
    ySuperscriptXOffset value
    ySuperscriptYOffset value
```

**Comment by MariannaPaszkowska** [comment]
Should we also keep superscript, subscript, and strikeout values compatible? 
What's your advice @dberlow? I'm aware that the wider design space might impact those decisions.

GSv10: 
OS/2:
```
    sxHeight value="510"
    sCapHeight value="716"

    ySubscriptXSize value="650"
    ySubscriptYSize value="600"
    ySubscriptXOffset value="0"  and ySubscriptXOffset value="-13" for italic
    ySubscriptYOffset value="75"
    
    ySuperscriptXSize value="650"
    ySuperscriptYSize value="600"
    ySuperscriptXOffset value="0" and ySuperscriptXOffset value="62" for italic
    ySuperscriptYOffset value="350"

    yStrikeoutSize value="84"
    yStrikeoutPosition value="306"
```

CC @chrissimpkins @davelab6

**Comment by dberlow** [comment]
Marianna,
In GSF,
… in general  all of our values are twice the values of Google sans because of the units per em change. When i write values can match, i mean after 2x multiply.
…numerators it will be used to create denominators fractions and possibly other small figures grow in height, as the opsz reduces for legibility down to opsz 6,  and spacial economy up to opsz144
… we recommend all small figures do the same, as at small opsz, the broad wght axis has need of larger glyphs to work well
…we think the italic  offsets of super and sub scripts don't apply, but are not sure what those offsets are meant for in roman, and are not needed in italic?
… opsz6 l.c. Ascenders exceed UC to ensure legible uc I vs lc l differentiation as other differences diminish at small sizes.
… our xheights shrink as opsz increases, but the default matches
… our strikeout value can match
…generally, FB makes ascend + descent + line gap = upm. But GS and GSF sum  to 120% of upm(!), which is not clear to us. Have discussed this with Dave Crossland last year and did not receive an answer that was understandable.

Hope that helps. Let me know questions or issues.

**Comment by MariannaPaszkowska** [comment]
Thank you, @dberlow! I'll keep investigating and will report back.

**Comment by MariannaPaszkowska** [comment]
I'm trying to set Vertical Metrics requirements for GS Flex, and I want to understand if and how HarfBuzz and Figma use those OS/2 values. GS will be both the parent font (previously integrated) and our fallback font, and I wonder how disruptive it would be if we changed those values in GS Flex. @simoncozens and @m4rc1e, I thought you might be able to help me.

OS/2 values that I'm investigating:
```
    sxHeight value
    sCapHeight value

    ySubscriptXSize value
    ySubscriptYSize value
    ySubscriptXOffset value
    ySubscriptYOffset value
    
    ySuperscriptXSize value
    ySuperscriptYSize value
    ySuperscriptXOffset value
    ySuperscriptYOffset value
```
I saw them mentioned here: https://harfbuzz.github.io/harfbuzz-hb-ot-metrics.html#hb-ot-metrics-tag-t .

**Comment by tiroj** [comment]
> generally, FB makes ascend + descent + line gap = upm. But GS and GSF sum  to 120% of upm(!), which is not clear to us.

Are you sure about the first part of that? It is fairly typical for ascent+descent sum to UPM value (line height), but line gap is, as the name suggests, default interline leading. If all three values sum to UPM, then text is default solid-set without any leading.

Setting line gap to 20% of UPM height is also fairly typical for Latin fonts. As I recall, Monotype do that as a standard (I prefer a slightly more generous 25% since the places where default linespacing is most often used, e.g. word processing apps, tend also to longer line lengths).

**Comment by dberlow** [comment]
> Are you sure about the first part of that?﻿
﻿
Yes. I'm sure. If the three values add up to the upm, and the line gap is zero then they will set solid. And if the line gap is not zero then they will not. I almost never set the line gap to zero except when I’m doing boarder or ornaments that need v connection.

Your comments on leading are not very clear, but apps treat all fonts the same and do not know the best linespacing for a given size, column or style. So including leading in the font, via upm space is, to user experience, bogus. 

And none of this is not explained by the metrics of the font adding up to 120% of upm, does it.

**Comment by tiroj** [comment]
> If the three values add up to the upm, and the line gap is zero then they will set solid.

If the three values add up to the UPM, then text will set solid regardless of what the line gap or either of the other two values is, since the UPM _is_ the line height of the nominal text size. So what you seem to be saying is that you do not make fonts with any default leading value within the font metrics.

I thought my comment re. leading was pretty clear: having the value of the font vertical metrics sum to 120% of the UPM means a built-in 20% leading in the font metrics relative to text size so, e.g. text set at 10pt will have default leading of +2pt, i.e. ‘10 on 12’ setting. That is pretty normal for Latin fonts and, as noted, standard for some foundries such as Monotype.

**Comment by dberlow** [comment]
The app ads default line spacing to built in linespacing. So with leading built in how does and app know that?

I have never seen an application with default solid setting, you?

**Comment by tiroj** [comment]
> The app ads default line spacing to built in linespacing. So with leading built in how does and app know that?

What app?

> I have never seen an application with default solid setting, you?

Notepad? Wordpad? MS Word? Browsers when no linespacing is defined in CSS? All those use font metrics for interline spacing, and if the font metrics sum to the UPM, then text is set solid.

Here is a GS font with the vertical metrics changed to sum to the UPM value: the nominal text size = the baseline to baseline measurement, i.e. set solid. In MS Word, default ‘Single’ linespacing:

<img width="710" alt="image" src="https://user-images.githubusercontent.com/5614500/203632976-bb6000a2-1fec-4127-a4ba-f1aa4ae8ae11.png">

**Comment by dberlow** [comment]
totally correct. word is setting a font with zero linespacing, with zero linespacing. The fact that they call it single doesn’t make it not zero.

**Comment by MariannaPaszkowska** [comment]
@belluzj  After chatting with Simon I think we should keep Subscript and Superscript values consistent too.  
```
    ySubscriptXSize value
    ySubscriptYSize value
    ySubscriptXOffset value
    ySubscriptYOffset value
    
    ySuperscriptXSize value
    ySuperscriptYSize value
    ySuperscriptXOffset value
    ySuperscriptYOffset value
```

**Comment by belluzj** [comment]
Noted, @RickyDaMa and @madig will make sure that they match (possibly with a fontbakery check if relevant)

**Comment by chrissimpkins** [comment]
Let's add the updates to the work in progress sources now so that we review files built with the correct v metrics.

**Comment by madig** [comment]
Super- and subscripts will be tested for in #101.

**Comment by madig** [comment]
The current tests say this about various values in https://github.com/FontBureau/fb-GoogleSansFlex/commit/fcb76df7acb43656641a6208a1de69014ddc9ade uprights:

* hhea.ascender should be 1932
* hhea.descender should be -572
* OS/2.sTypoAscender should be 1932
* OS/2.sTypoDescender should be -572
* OS/2.usWinAscent should be 2646
* OS/2.usWinDescent should be 2158
* OS/2.yStrikeoutPosition should be 612
* OS/2.yStrikeoutSize should be 168
* post.underlinePosition should be -320
* post.underlineThickness should be 168

The values are scaled from GS's 1000 upM to GSF's 2000 upM.

@MariannaPaszkowska as discussed.

**Comment by MariannaPaszkowska** [comment]
@sannorozco, @dberlow, above are the vertical metric values we calculated with @madig. Could you include them in your sources? Of course, if you have any feedback, let us know.

**Comment by dberlow** [comment]
Are these for certain?;OS/2.usWinAscent should be 2646OS/2.usWinDescent should be 2158They total beyond 200% of the units per em.

**Comment by madig** [comment]
We took the values from GS and doubled them (GS is 1000 upM, GSF is 2000). In GS, the values are `"OS/2.usWinAscent": 1323` and `"OS/2.usWinDescent": 1079`.

**Comment by chrissimpkins** [comment]
We set Win metrics just above and just below the actual max and min metrics for a given build, set the Use Typo Metrics bit flag, and fix our hhea and typo metrics across every build (should use the values in GS v10).  All linespacing values should be set to zero.  

This is the way.  :)

**Comment by MariannaPaszkowska** [comment]
Correct @chrissimpkins My mistake, apologies. The Win metrics will be computed. I should have excluded them here, like I did in the issue description. 

Those are the values that we need to import into the sources:
hhea.ascender should be 1932
hhea.descender should be -572
OS/2.sTypoAscender should be 1932
OS/2.sTypoDescender should be -572
OS/2.yStrikeoutPosition should be 612
OS/2.yStrikeoutSize should be 168
post.underlinePosition should be -320
post.underlineThickness should be 168

In OS/2. table, the fsSelection bit 7 'Use Typo Metrics' should be on.

@sannorozco @dberlow

**Comment by tiroj** [comment]
How do those OS/2 WinAscent and WinDescent metrics relate to the yMax and yMin values of tallest and deepest glyphs? As they are now in GS? As they are anticipated in the extended script and language coverage of GS Flex? Taking into account effects of GPOS mark positioning above and below or not?

**Comment by chrissimpkins** [comment]
> How do those OS/2 WinAscent and WinDescent metrics relate to the yMax and yMin values of tallest and deepest glyphs? As they are now in GS? As they are anticipated in the extended script and language coverage of GS Flex? Taking into account effects of GPOS mark positioning above and below or not?

That'a a great question John.  It is a simple adjustment to one unit above and below the global yMax and yMin set by the compiler as I recall.  Do you have an approach that better estimates fully shaped y max and min dimensions? We're open to adjusting them to the best set of values with each change in y dimensions as new tall/deep design lands.

**Comment by sannorozco** [comment]
I’ll update the sources tonight that no one will be updating the sources.

> Those are the values that we need to import into the sources: hhea.ascender should be 1932 hhea.descender should be -572 OS/2.sTypoAscender should be 1932 OS/2.sTypoDescender should be -572 OS/2.yStrikeoutPosition should be 612 OS/2.yStrikeoutSize should be 168 post.underlinePosition should be -320 post.underlineThickness should be 168
> 
> In OS/2. table, the fsSelection bit 7 'Use Typo Metrics' should be on.
> 
> @sannorozco @dberlow

**Comment by tiroj** [comment]
> That'a a great question John. It is a simple adjustment to one unit above and below the global yMax and yMin set by the compiler as I recall. Do you have an approach that better estimates fully shaped y max and min dimensions?

I have not examined the sources so don’t know what the current tallest and deepest glyphs are, but the OS/2 Win metrics values look fairly generous in terms of typical text characters, so I am guessing that the glyphs that establish yMax and yMin are possibly non-alphabetic. In that case, you _may_ not have to worry about shaping height, but these are the things to bear in mind generally:

In theory, renderers are supposed to rasterise bitmaps first and then apply GPOS, so it is the pre-painted bitmaps that are positioned, and—also in theory—this means that bitmaps that get positioned beyond the OS/2 Win metrics limits should not be clipped if their pre-GPOS location is witin those limits. But we’ve found that this is not reliable, because various environments apply clipping in some situations, e.g. in proximity to frame edges. A single environment might clip positioned bitmaps in some places and not in others, as shown here in an early test of Nirmala UI in Wndows dialogues:
<img width="1378" alt="image" src="https://user-images.githubusercontent.com/5614500/208500922-b65ad6c0-530b-4640-b53f-dfa8b250a1d0.png">

Various scripts involve vertical stacking of marks as part of shaping, in which one or more of the marks involved may be supbscript or superscript forms of letter characters and, depending on the design, might be significantly larger than what European typographers think of as ‘marks’ (a notable example is Javanese, in which the subscript forms of letters are conventionally the same size as the base forms). Most writing systems tend either not to stack beyond two marks in height, or provide contextual mechanisms such as horizontal alternate forms (e.g. the postscript form of –Ra in Telugu, which is used contextually when preceded by a subscript). But such systems tend to evolve from the phonology of particular languages, and foreign loanwords or other languages (e.g. Sanskrit when written in South Indian scripts) may produce taller stacks that exceed the OS/2 Win metrics limits in a font. And there are exceptions to the general tendency, with Javanese again being a notatable case in which it is not unusual for the descender space to be occupied by more than double the base letter height, and some forms of Tibetan script involve fairly frequent three-letter stacks, or more in the classical language.

With regard to linespacing metrics, note that the OS/2 fsSelection bit 7 mechanism is a great example of Microsoft’s habit of specifying font data while under-specifying implementation. This means that the bit is weirdly interpreted in some environments, notably MS Office apps. The whole point of the bit when we specified it in 2004 was that apps should use the OS/2 Type metrics for linespacing _so that the OS/2 Win metrics could be independently set and perform their originally intended role of defining the non-clipping zone._ But what actually happens in e.g. MS Word is that instead of erroneously using the Win metrics for both linespacing and to determine the limits beyond which glyphs get clipped, now the Typo metrics are erroneously used for both.🙄

**Comment by tiroj** [comment]
[Is there a spec for GS Flex that explains how it is planned to be used and in what environments it is expected to work? I don’t have an understanding of the overall purpose of the project, so am only providing general comments on the kind of things I would be watching out for.]

**Comment by sannorozco** [comment]
Metrics have been updated.

**Comment by MariannaPaszkowska** [comment]
Thank you @sannorozco

**Comment by MariannaPaszkowska** [comment]
This is very helpful, thank you @tiroj
