### ISSUE TITLE
Options for GSF italic

### ISSUE THREAD

**Issue by dberlow** [googlefonts/googlesans-flex#50]
The current choice (2 fonts):
Roman and italic
weight (1 to 1000, default: 400)
width (25 to 151, default: 100)
opsz (6 to 144, default: 18)
GRAD (-50 to +50, default: 0)
ROND (0 to 100, default: 0)

Option 1 (1 font);
Roman with slant (slnt)
weight (1 to 1000, default: 400)
width (25 to 151, default: 100)
opsz (6 to 144, default: 18)
GRAD (-50 to +50, default: 0)
ROND (0 to 100, default: 0)
slnt (0 to -10, default: 0)

Option 2  (1 font);
Roman with Italic (ital)
weight (1 to 1000, default: 400)
width (25 to 151, default: 100)
opsz (6 to 144, default: 18)
GRAD (-50 to +50, default: 0)
ROND (0 to 100, default: 0)
ital (all glyph substitution)

**Comment by davelab6** [comment]
I was just writing to a prospective early adopter team,

> In Roboto Flex, we have a 'Slant' axis, and in GS Flex (AFAIK) we haven't decided if we will package it as 2 fonts, Roman and Italic, or as 1 font with a Roman and a Slant axis.
> 
> (There is also an option for 1 font with an Italic axis, but this sadly is not as well supported as Slant, see [https://arrowtype.github.io/vf-slnt-test/](https://www.google.com/url?q=https://arrowtype.github.io/vf-slnt-test/&sa=D&source=editors&ust=1671007540015942&usg=AOvVaw1EzXqQXSKymyUcZ23XcNt0))
> 
> This decision is being tracked in [this issue]
> 
> So this is very useful feedback to know that you would prefer a Slant axis packaging :)

Since this is a packaging thing, and given Italic is on hold at the moment, I don't think any changes need to made to https://github.com/googlefonts/googlesans-flex/tree/main/sources/italic until much later in the project, but I was happy to find this issue as a good place to post this 'user feedback' that being able to interpolate - animate - from roman to italic is desirable.

**Comment by davelab6** [comment]
@MariannaPaszkowska whats the debate? :) 

The GF product as a whole is committed to `slnt` as the way to provide continuously interpolated italic styles; Evan is ramping up on the work needed for this ahead, but I don't see that changing. Since users want to interpolate from roman to italic, I believe we must work towards `slnt` as the way to package the project.

**Comment by MariannaPaszkowska** [comment]
I think we wanted to hear back from the teams about the file size before taking a final decision about this @chrissimpkins

**Comment by dberlow** [comment]
We'll be able to tell definitively in a short time whether the sum
file size of two variables or one combined variable is larger?
