### ISSUE TITLE
Dealing with incomplete axis coverage of a Designspace

### ISSUE THREAD

**Issue by madig** [googlefonts/googlesans-flex#52]
IIUC, future script expansions may not contain full coverage of all axes at some point in time. The compilation pipeline however expects all glyphs slots to be filled in for all axes. In Google Sans, where we have the same problem, I set up the scripting to copy glyphs around across UFOs, which is obviously suboptimal and leads to things getting out of sync unless you're careful.

I think a better way would be have some code do the copying how we want it before the sources hit the compiler. I'm not sure how best to do that (plain script? ufo2ft filter?) and the answer may depend on whether we want to keep using gftools build. We would be interested in this functionality, too, for internal projects.

In Fontgardener, I expect this "business logic" to be done outside, so we need to think about it either way.

**Comment by dberlow** [comment]
> future script expansions may not contain full coverage
﻿
The future is here with the designspace disparities between Black Foundry’s GSF CJK and FB’s GSF LGC.

In Q1 of 2022, we met discussed this issue and afterwards FB advised Google of the options for each scripts project spec vs the product spec’s possibilities, and since product decisions may not be made based always on “business logic”, we just call the two logics “project” and “product”.

In the end, products will have to be defined by whether or not the design space is clipped to the lowest common denominator of the scripts contained or stretched, as apps currently deal with font size input outside range of opsz, until the ds of all the product’s 
scripts match.

**Comment by dberlow** [comment]
@chrissimpkins and @davelab6 Please review
