### ISSUE TITLE
Build workflow - branches

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#53]
Hi @sannorozco, @dberlow, 
Thank you for the GSF Alpha1.0 release! 
Together with the DaMa team, we're setting up a build workflow. The idea is that you could keep daily work in one branch and push finished work into an import branch. Then a build workflow, when triggered, will automatically create a PR into the main. We want to keep releases for our internal milestones. Can we find a way to make it work? We can discuss the details here. 

CC @chrissimpkins @belluzj

**Comment by RickyDaMa** [comment]
That would work well from our perspective. I would caution over calling the FB 'ready to merge' branch an import branch, because that's the naming scheme given to the PR branches when trying to merge FB changes into main (though this could be changed if necessary).

Apologies for essentially bikeshedding, but may I suggest `in-progress` and `ready` for the two FB branches?

**Comment by RickyDaMa** [comment]
Adding diagram for clarity:

![Branch naming scheme & flow](https://user-images.githubusercontent.com/113340856/204501960-dd7ef256-509d-4a6a-91d1-3a954cf25b29.png)

(for the most complete diagram for the entire workflow, see [Jany's](https://github.com/googlefonts/googlesans-flex/issues/28#issuecomment-1314037465))
