### ISSUE TITLE
6-85-1000-Rond0 sparse is really sparse?

### ISSUE THREAD

**Issue by octaviopardo** [googlefonts/googlesans-flex#563]
6-85-1000-ROND0-sparse has 518 glyphs (vs 520 in the other masters). Is it really a sparse master? should all the glyphs be considered?
@sannorozco @dberlow @MariannaPaszkowska

**Comment by dberlow** [comment]
I've never put such a source in any version of the designspace I've worked
on.

opsz6 has round sides when it condenses, instead of straight sides like
opsz18 and above;
so wdth50 and wdth85 are not needed as full sources at opsz6.

It must be a sparse master for something that was not made very sparse.
Santiago must know what glyph(s) is/are involved.

Cheers,
David

**Comment by sannorozco** [comment]
Hey @octaviopardo! this is already sparsified on the Roman, have you imported into Italic?

https://github.com/googlefonts/googlesans-flex/issues/520

**Comment by octaviopardo** [comment]
aaah you are right, thanks @sannorozco
