### ISSUE TITLE
define glyph list for v1.2

### ISSUE THREAD

**Issue by octaviopardo** [googlefonts/googlesans-flex#587]
Hi @MariannaPaszkowska would it make sense to define a def glyph list, so we can erase the unnecessary glyphs from the UFOs? It was suggested that g.alt was there but was not really required.

**Comment by MariannaPaszkowska** [comment]
We prioritise the language coverage list rather than a definitive glyph list. We have some glyph lists - https://github.com/googlefonts/googlesans-flex/issues/41, https://github.com/googlefonts/googlesans-flex/issues/72 - but those don't specify a definitive character set. In the sources there might be some additional substratum/construct glyphs (those unencoded, not referenced in the OT features - used only as components).

Targeted language coverage is as defined https://github.com/googlefonts/googlesans-flex/issues/41:
```
Basque		eus
Catalan		cat
Croatian	hrv
Czech		ces
Danish		dan
Dutch		nld
English		eng
Estonian 	ekk
Finnish		fin
French		fra
Galician	glg
German		deu
Hungarian	hun
Icelandic	isl
Irish		gle
Italian		ita
Latvian 	lvs
Lithuanian	lit
Malaysian	zlm
Norwegian	nor
Polish		pol
Portuguese	por
Romanian	ron
Slovak		slk
Slovenian	slv
Spanish		spa
Swedish		swe
Swiss German	gsw
Turkish		tur
Welsh		cym
```

CC @chrissimpkins @davelab6 @dberlow

**Comment by davelab6** [comment]
(edit: Moving to new issue)

The `g.alt` (and `a.alt`) is important as it was specifically requested by Hilary, the GF UX Research Lead.
