### ISSUE TITLE
Commit level build and zip archive prep is not functioning in the Font Bureau branch

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/googlesans-flex#59]
https://github.com/googlefonts/googlesans-flex/actions/runs/3550848630/jobs/5964580971

Can we still support the commit-by-commit builds and zip archive prep so long as the expected designspace path is available in the branch @RickyDaMa?

**Comment by RickyDaMa** [comment]
Hi Chris, yes we can. However, because in `fb-wip` the designspaces file have changed location, the CI fails. This will need to be updated in the `sources/config.yaml` file - as this is what the CI uses to determine the designspaces to build (and where they are located).

If you'd like, I can make it point to the designspace in the `roman` folder on their branch? ([here](https://github.com/googlefonts/googlesans-flex/blob/fb-wip/sources/roman/GoogleSansFlex.designspace))

**Comment by MariannaPaszkowska** [comment]
Hi @RickyDaMa, this commit fails too. https://github.com/googlefonts/googlesans-flex/commit/df0580f2edd6a1def7ed72f77a26abe1cd11eeaf 

Names of the sources from FB are meaningful and point to the space in the design space - if that helps. Otherwise, yes, please point to that designspace in the roman folder on their branch.

CC @belluzj @madig

**Comment by RickyDaMa** [comment]
> because in `fb-wip` the designspaces file have changed location, the CI fails. This will need to be updated in the `sources/config.yaml` file

This was still the case. I've updated the config file to build both their roman and italic designspaces and pushed it to their branch. The pipeline now succeeds

**Comment by MariannaPaszkowska** [comment]
@madig is this compatible with your PR https://github.com/googlefonts/googlesans-flex/pull/65 ?

**Comment by madig** [comment]
Yes, the changes in fb-wip are independent because we look at the Designspace files directly rather than the config files.

**Comment by MariannaPaszkowska** [comment]
Hi, thanks for the quick fixes! There are still some build errors, and the Italic VF font is not building. Could you please look into that? @RickyDaMa @madig 
example: annotations here https://github.com/googlefonts/googlesans-flex/actions/runs/3601453363

**Comment by madig** [comment]
That specific error is fontbakery complaining about stuff. It will probably continue to do so until we hit the release candidate stage.

The italics aren't building because this PR does not pull new sources (the workflow needs to run for that) and is also not set up to do so. I can set it up though.

**Comment by MariannaPaszkowska** [comment]
Thank you @madig, we changed the project scope and are moving the Italics after the March release.
