### ISSUE TITLE
Fix issues in master 17opsz 400wght 25wdth ROND100 and ROND0

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#621]
- [x] interpolation (issues also in wght1):
`r  ij `

- [x] outline harmonisation 
` a c e f g s `

- [x] anchor positioning
`ÄËÏüÿä ŮůÅŮåů İċĊġĖėŻż`

<img width="1065" alt="Screenshot 2023-07-04 at 5 13 59 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/8a7e460d-5300-41bd-9c38-e638223ff4d0">

Tested build:
https://github.com/googlefonts/googlesans-flex/actions/runs/5455486387

**Comment by Bogidar** [comment]
This rounded its not on the design space right?

**Comment by octaviopardo** [comment]
It s not, but we are seeing a couple of weird things in the interpolations that we ll be reviewing in between today and next week. The best thing to do now I think is to get the latest version of a build (as soon as there is one) and check those coordinates to see if the problem with the anchor's position remains (Im pretty sure it does not). Then we will check the relation in between the upright and the italic to see if the rond axis behaves equally (we already know it does not in certain areas of the space).

**Comment by octaviopardo** [comment]
Seen and I think this can be closed. The outlines are not ideal, but that is because the opsz17 R100 is a pure interpolation in between a sharp (opsz6 R100 is actually sharp) and a Rounded (opsz18 R100). So the fixes are not clear where should be done, or even if they can be done. 
![Captura de pantalla 2023-07-10 a las 10 53 49](https://github.com/googlefonts/googlesans-flex/assets/2181684/2f4fe609-fd84-4293-a00d-d2f7abf6448b)
