### ISSUE TITLE
Euro sign outline issues

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#644]
Please also check the tabular one.
<img width="927" alt="Screenshot 2023-07-20 at 10 26 49 AM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/54f12e1d-20f0-4c52-be4f-8bab5ab89aed">
<img width="921" alt="Screenshot 2023-07-20 at 10 26 42 AM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/9d9e0618-60f7-45df-86dc-b827c98437f3">

**Comment by octaviopardo** [comment]
We are looking at this, but question @MariannaPaszkowska , the $ and ¢ that have the wrong bars in your image, do not look like that in the last build. How did that happen?

**Comment by MariannaPaszkowska** [comment]
@madig @belluzj could this happen during the build that we're not importing one of the intermediate masters?

**Comment by octaviopardo** [comment]
The issue is quite complex to solve. I 've spent the whole morning doing research and here are the conclusions:

The issue seems to be in the relative position of the points at opsz6-wdth25-wght400-xxxx. There is a sparse master influencing the € symbol in opsz6-wdth85-wght1000 but it does not seem to have much influence on the issue (screenshots attached with corresponding UFOs being muted)
![Captura de pantalla 2023-07-21 a las 14 07 36](https://github.com/googlefonts/googlesans-flex/assets/2181684/561208bf-aa7c-4949-817d-89a53a0634fe)
![Captura de pantalla 2023-07-21 a las 14 07 56](https://github.com/googlefonts/googlesans-flex/assets/2181684/04d8e890-d7ba-4872-a75c-c8ca1e09b888)
![Captura de pantalla 2023-07-21 a las 14 08 21](https://github.com/googlefonts/googlesans-flex/assets/2181684/b4fa4ae4-0302-4f97-b27b-bbf46d008d92)

Before doing all these tests, I also tried to make simple build-in glyphs (image attached). Curiously, glyphs build the symbol fine, so either the building in the repo is fine and this is an issue of design @dberlow ; or the design is fine and this seems to be a problem with the building in the repo @madig ; Besides, glyphs is doing something fine-but-wrong, o just fine @schriftgestalt :)

(top, glyphs export, bottom repo build)
![Captura de pantalla 2023-07-21 a las 14 18 39](https://github.com/googlefonts/googlesans-flex/assets/2181684/55153554-fd5c-4b9f-8ba4-5e6eb9282e23)

**Comment by madig** [comment]
I built both main and the italics-1.002 branch and I can see a broken Euro at the specified locations on both, so this doesn't seem to be an import issue.

I'll try and follow what Octavio posted.

**Comment by davelab6** [comment]
Looks like the k issue in #430

**Comment by madig** [comment]
Yeah. If I cut down the uprights Designspace to just opsz6-wdth25-wght400, opsz6-wdth100-wght400 and opsz6-wdth151-wght400 and change the wdth while wght=400, opsz=6, ROND=0 stays the same, the problem is gone. I'm going to look for holes in the Euro design space.

**Comment by madig** [comment]
Here's where the data for Euro comes from at location `{"Weight": 400, "Width": 43, "Optical Size": 6, "Roundness": 0}`; contribution means how much of the source is blended into the result:

| Source | Contribution |
| ------ | ------------ |
| GoogleSansFlex-opsz6-wdth25-wght1-ROND0.ufo | 100% |
| GoogleSansFlex-opsz6-wdth85-wght1000-ROND0-SPARSE.ufo | 30% |
| GoogleSansFlex-opsz6-wdth100-wght1-ROND0.ufo | 72% |
| GoogleSansFlex-opsz6-wdth100-wght400-ROND0.ufo | 28% |
| GoogleSansFlex-opsz6-wdth151-wght1-ROND0.ufo | 100% |
| GoogleSansFlex-opsz18-wdth151-wght1000-ROND0.ufo | 76% |

I'll play a bit with the sources to see if I can turn off the poltergeist.

**Comment by madig** [comment]
Random finding: Why is GoogleSansFlex-opsz6-wdth85-wght1000-ROND0-SPARSE.ufo used for ROND0 and ROND100?

**Comment by madig** [comment]
After half a day of fiddling with this with Jany, we came up short. We suspect it's the same story as the crooked "k". More next week.

**Comment by MariannaPaszkowska** [comment]
@octavio will add sparse masters (upright, italic, sharp and ROND)

**Comment by octaviopardo** [comment]
On green the area where the issue is present. I have added sparse masters at the opsz6-width50 weights 1,400 & 1000 and that fixes the error in that plane of the interpolation space. Now I m working on fixing the other side of the cube and hoping that will solve all the intermediate space
![20230725_165423](https://github.com/googlefonts/googlesans-flex/assets/2181684/d783e53d-cb33-4ac6-beea-477ae09621fc)

**Comment by MariannaPaszkowska** [comment]
Thanks for the updates! It is fixed in the upright and italic, but not into the merged (slnt) font:
@madig @belluzj @octaviopardo Is this caused by the sources or by the build?
<img width="623" alt="Screenshot 2023-07-27 at 4 15 23 PM" src="https://github.com/googlefonts/googlesans-flex/assets/22956348/aca31058-29af-402f-86de-da18d54a2b51">

**Comment by casasin** [comment]
Using the .designspace files in the `it-ad-wip-italic-v1.002` branch inside "sources", "sources/regular" and "sources/italic" gives me this:
<img width="616" alt="Captura de pantalla 2023-07-27 a les 15 34 20" src="https://github.com/googlefonts/googlesans-flex/assets/1898042/9baa28dd-f7a4-4e60-a8d1-ea85f1c32772">

**Comment by madig** [comment]
The full Designspace is manually maintained. I regenerated it in https://github.com/googlefonts/googlesans-flex/pull/668.

**Comment by MariannaPaszkowska** [comment]
Thank you, everyone for your hard work on solving this issue. I confirm that this is fixed in the latest build: https://github.com/googlefonts/googlesans-flex/actions/runs/5682175684
