### ISSUE TITLE
colon, colon.tf and colon time

### ISSUE THREAD

**Issue by octaviopardo** [googlefonts/googlesans-flex#717]
So the font has three different colons (and two semicolons): colon, colon.tf and colon .time. The particularity in colon.time is that it is aligned so the figures look nice in a clock set up. However the colon.tf is in many cases in the same position. It looks nice and makes sense when use in the context of figures, but it is simply out of alignment with the semicolon.tf. Any thoughts on that? Shall we keep it this way? IMO I would not, I would keep the colon.tf aligned with the baseline
![unnamed-6](https://github.com/googlefonts/googlesans-flex/assets/2181684/2b5e82e8-7e0f-4c34-9e7a-e45ceb74f5bb)

**Comment by chrissimpkins** [comment]
#### for colon.tf:

Do we currently, or ever expect to, support anything tabular other than figures and currency symbols in this proportional family?  If not, IMO we align the colon.tf with figures where it is most likely to be used.  I can't imagine a scenario where a user formats adjacent proportional e.g., LC alphabetic forms next to a tabular colon form.  And if anyone out there happens to be doing that, I think that we can consider it very edge use case and not one that we need to support so that we can have consistency in the height alignments for tabular forms IMO.

#### for colon.time:

IIRC this is a proportionally spaced form and was meant for horizontal digital clock displays like `12:32pm`.  I believe that the contextual shaping support is in the calt feature.  This was a request from our product team designers and should remain figure height aligned.

**Comment by MariannaPaszkowska** [comment]
We discussed it internally and reached a decision: let's keep the colon.tf aligned vertically with figures (as is now). 
Reasoning: most likely users are setting it when working with number-heavy content.
CC @octaviopardo 
.
