### ISSUE TITLE
improve Shaperglot output

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#805]
Tasks:

- [x] 1. Test against our language target list.

- [ ] 2. Group reporting by:

a. Font supports language from our target list
b. Additionally font supports language
c. Font does not fully support language 

Target list [redacted]

**Comment by MariannaPaszkowska** [comment]
@RickyDaMa I added a target list in the issue description.

**Comment by MariannaPaszkowska** [comment]
related #684

**Comment by RickyDaMa** [comment]
@MariannaPaszkowska can you confirm what work there still is to be done for this issue, and if it's v2 release critical? Thanks

**Comment by chrissimpkins** [comment]
We would like to support a shaperglot-defined report of **all languages that are supported in the font family**. This is an expansion of our current shaperglot `check` based QA test to confirm that target priority languages are supported.  My understanding is that this issue is still open and that this needs to be implemented in the CI environment.

**Comment by RickyDaMa** [comment]
https://github.com/googlefonts/shaperglot/releases/tag/v0.5.0 adds `--group` and `--csv`
