### ISSUE TITLE
`percent.tf` (1596) has different width than `zero.tf` (1413)

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#812]
`percent.tf` (1596) has different width than `zero.tf` (1413)

tested data: https://github.com/googlefonts/googlesans-flex/actions/runs/7670878627

**Comment by schriftgestalt** [comment]
That is an interesting find. The percent.tf has a width metrics key. But it is build from components with automatic layout. That supersedes the metrics key. I can adjust that so that after the automatic layout, the metrics key is applied and the difference is applied evenly on both sides. But as it is potentially big change (a lot people might have metrics keys in auto aligned glyphs without realizing it), I probably will put it into G4, only. 

But while looking at the percent.tf, I found this:
<img width="924" alt="Bildschirmfoto 2024-01-29 um 10 44 36" src="https://github.com/googlefonts/googlesans-flex/assets/174660/3e4317f9-d483-4ad1-9669-0ef3ac94b9c5">
It seems that the "small numbers" are not slanted?

**Comment by octaviopardo** [comment]
Do not touch anything in G3. I ve fixed the issue, while keeping the automatic alignment, by adjusting the metrics of the individual components. It should be good now

**Comment by MariannaPaszkowska** [comment]
many thanks, fixed in #825
