### ISSUE TITLE
Create more granular CI job labels to locate reports/data more easily

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/googlesans-flex#890]
Our Flex CI run logs as of the v2.000 release commit are now nearly 10,000 lines long.  This makes it difficult to identify individual reports in the log output.  It would be helpful for the CI UI to show a more granular categorization of the output so that you can click on the info that you want and have it open directly to that logging output.  e.g., for fontbakery check output, shaperglot output, font-size output.  The current grouping is under "test".

Let's give some thought to how we might approach this as part of the next phase in development.

![9xwKr6urzJ2Rodd](https://github.com/googlefonts/googlesans-flex/assets/4249591/12f07be6-58c8-488d-aa92-2f13cff170e1)

**Comment by RickyDaMa** [comment]
This is potentially quite difficult to make happen, just due to the way I've structured the workflows to have them as re-usable components (e.g. this big tests block is used in three workflows: build-glyphs, build, and import)

There's potentially one way I can make this work; I'd have to experiment and see

**Comment by belluzj** [comment]
Idea: emit "groups" in the logs? https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#grouping-log-lines

**Comment by RickyDaMa** [comment]
@belluzj the groups here effectively create a collapsible region within the log lines, not a collapsible heading. I'm already using them in various places (e.g. creating venvs and installing stuff into them)

They're nice for hiding stuff you don't want to see when power scrolling through the logs, but not that useful for making logs more readable when your issue is the quantity of output and it's all somewhat important

**Comment by RickyDaMa** [comment]
![image](https://github.com/googlefonts/googlesans-flex/assets/113340856/830f25f3-c47f-4def-885a-e3e08718fc6d)

Good news, everyone! It seems like this should be possible
