### ISSUE TITLE
Adjust STAT table in workspace slices

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#949]
Hi there, I prepared the 2.002 release with workspace fonts and when reviewing I noticed that the STAT tables in those fonts have some artefacts from the original VF. 
Here is an example (ttx): 
SuperCondensed Italic has all axes still stated there, and I am not sure if we should be keeping 144pt instance:
```
 <STAT>
    <Version value="0x00010001"/>
    <DesignAxisRecordSize value="8"/>
    <!-- DesignAxisCount=6 -->
    <DesignAxisRecord>
      <Axis index="0">
        <AxisTag value="opsz"/>
        <AxisNameID value="256"/>  <!-- Optical Size -->
        <AxisOrdering value="0"/>
      </Axis>
      <Axis index="1">
        <AxisTag value="wdth"/>
        <AxisNameID value="257"/>  <!-- Width -->
        <AxisOrdering value="1"/>
      </Axis>
      <Axis index="2">
        <AxisTag value="wght"/>
        <AxisNameID value="258"/>  <!-- Weight -->
        <AxisOrdering value="2"/>
      </Axis>
      <Axis index="3">
        <AxisTag value="GRAD"/>
        <AxisNameID value="259"/>  <!-- Grade -->
        <AxisOrdering value="3"/>
      </Axis>
      <Axis index="4">
        <AxisTag value="ROND"/>
        <AxisNameID value="260"/>  <!-- Roundness -->
        <AxisOrdering value="4"/>
      </Axis>
      <Axis index="5">
        <AxisTag value="ital"/>
        <AxisNameID value="261"/>  <!-- Italic -->
        <AxisOrdering value="5"/>
      </Axis>
    </DesignAxisRecord>
    <!-- AxisValueCount=14 -->
    <AxisValueArray>
      <AxisValue index="0" Format="1">
        <AxisIndex value="0"/>
        <Flags value="0"/>
        <ValueNameID value="319"/>  <!-- 144pt -->
        <Value value="144.0"/>
      </AxisValue>
      <AxisValue index="1" Format="1">
        <AxisIndex value="1"/>
        <Flags value="0"/>
        <ValueNameID value="320"/>  <!-- SuperCondensed -->
        <Value value="25.0"/>
      </AxisValue>
      <AxisValue index="2" Format="1">
        <AxisIndex value="2"/>
        <Flags value="0"/>
        <ValueNameID value="282"/>  <!-- Thin -->
        <Value value="100.0"/>
      </AxisValue>
      <AxisValue index="3" Format="1">
        <AxisIndex value="2"/>
        <Flags value="0"/>
        <ValueNameID value="283"/>  <!-- ExtraLight -->
        <Value value="200.0"/>
      </AxisValue>
      <AxisValue index="4" Format="1">
        <AxisIndex value="2"/>
        <Flags value="0"/>
        <ValueNameID value="284"/>  <!-- Light -->
        <Value value="300.0"/>
      </AxisValue>
      <AxisValue index="5" Format="3">
        <AxisIndex value="2"/>
        <Flags value="2"/>  <!-- ElidableAxisValueName -->
        <ValueNameID value="285"/>  <!-- Regular -->
        <Value value="400.0"/>
        <LinkedValue value="700.0"/>
      </AxisValue>
      <AxisValue index="6" Format="1">
        <AxisIndex value="2"/>
        <Flags value="0"/>
        <ValueNameID value="286"/>  <!-- Medium -->
        <Value value="500.0"/>
      </AxisValue>
      <AxisValue index="7" Format="1">
        <AxisIndex value="2"/>
        <Flags value="0"/>
        <ValueNameID value="287"/>  <!-- SemiBold -->
        <Value value="600.0"/>
      </AxisValue>
      <AxisValue index="8" Format="1">
        <AxisIndex value="2"/>
        <Flags value="0"/>
        <ValueNameID value="288"/>  <!-- Bold -->
        <Value value="700.0"/>
      </AxisValue>
      <AxisValue index="9" Format="1">
        <AxisIndex value="2"/>
        <Flags value="0"/>
        <ValueNameID value="289"/>  <!-- ExtraBold -->
        <Value value="800.0"/>
      </AxisValue>
      <AxisValue index="10" Format="1">
        <AxisIndex value="2"/>
        <Flags value="0"/>
        <ValueNameID value="290"/>  <!-- Black -->
        <Value value="900.0"/>
      </AxisValue>
      <AxisValue index="11" Format="1">
        <AxisIndex value="3"/>
        <Flags value="2"/>  <!-- ElidableAxisValueName -->
        <ValueNameID value="325"/>  <!-- Normal -->
        <Value value="0.0"/>
      </AxisValue>
      <AxisValue index="12" Format="1">
        <AxisIndex value="4"/>
        <Flags value="2"/>  <!-- ElidableAxisValueName -->
        <ValueNameID value="331"/>  <!-- Default -->
        <Value value="0.0"/>
      </AxisValue>
      <AxisValue index="13" Format="1">
        <AxisIndex value="5"/>
        <Flags value="0"/>
        <ValueNameID value="294"/>  <!-- Italic -->
        <Value value="1.0"/>
      </AxisValue>
    </AxisValueArray>
    <ElidedFallbackNameID value="2"/>  <!-- Italic -->
  </STAT>
```

fvar looks good. Could you please have a look?

cc @davelab6

**Comment by belluzj** [comment]
@MariannaPaszkowska I believe it's OK for the STAT table to have more information about the axes of the family than there are axes in the fvar table. A very common example is when you have an upright VF and an italic VF part of the same family, none of the two VFs have an "ital" axis in their fvar, but both should have "ital" records in their STAT, to be linked together. The spec encourages this here: https://learn.microsoft.com/en-us/typography/opentype/spec/stat#axis-records

![image](https://github.com/googlefonts/googlesans-flex/assets/3616772/8e2ba529-7009-4b63-ac14-1c5c97dbe7d4)

You could argue that, as we're not planning to "complete the family" with other opsz values, there's no point in having that STAT entry for opsz. But I would say it shouldn't hurt to keep them here, as it's descriptive and shows that despite the fvar axes having been removed, these workspace fonts have a location along the axes that have been removed, so it's "interesting information" if anything.

It's also the default behaviour of the varLib instancer to not drop Axis records, and keep AxisValue records that match the location/range of the subset font.

Let me know if that answers your question, thanks in advance!

**Comment by MariannaPaszkowska** [comment]
Ok, so you'd want to leave them in order to allow linking of the family via STAT (is this implemented anywhere?). But doesn't this require different flags for the subtables?

**Comment by belluzj** [comment]
> is this implemented anywhere?

The italic linking is implemented in some apps (with the italic button), the others axis types probably not, or I'm not sure in which capacity.

> But doesn't this require different flags for the subtables?

The italic thing requires the use of the Format 3 AxisValue with a linkedValue:

![image](https://github.com/googlefonts/googlesans-flex/assets/3616772/536e48ef-fa4c-44cf-bee6-0a669460d8d6)

The linkedValue mechanism seems only intended to implement the old "Bold" and "Italic" buttons of word processors. The spec doesn't show example for other types of axes.

Among the other flags described in the spec, the only one that is relevant to linking across TTFs using STAT is OLDER_SIBLING_FONT_ATTRIBUTE.

![image](https://github.com/googlefonts/googlesans-flex/assets/3616772/775f78d7-303f-4462-8889-9016ccf78f7e)

I understand it as: if we release a family which doesn't have an optical size axis, and then later we extend that family with an optical size axis (by considering that the previously released designed was "Text" and the new design is "Display"), the previously released TTFs won't have a mention of the opsz axis, and if they're installed alongside a new TTF that does include opsz, then the new TTF can say, with OLDER_SIBLING_FONT_ATTRIBUTE, this: "please consider any TTF of my family, that doesn't have opsz information, to be "Text".

So it's a mechanism for when you extend a font family later, which is not our case (because instead of extending, we're subsetting, and we know already where we are on the style axes that we're subsetting at a specific point).

I'm still thinking that it's not an error to have extra STAT information about where the font is located on axes like opsz, even if the font family won't have other opsz values. Indeed, the Workspace family named "Google Sans Flex SuperCondensed" will only ever have an optical size of 144pt, so will never need to be linked by STAT to other VFs of the same "Google Sans Flex SuperCondensed" family at other optical sizes.

But I can see your point of view, which I suppose to be: this data is useless because we'll never need it, so it needs to be removed. If that's your final opinion I will remove the STAT entries for anything other than Weight (because we have a weight axis) or Italic (because we do use that one to link the Upright and Italic files). Let me know if that's your final opinion and I'll push a fix.

**Comment by MariannaPaszkowska** [comment]
Ok, I'll guess it's not very costly to keep it in, and in some possible future it might be helpful... So I gather it's ok to keep it in. 
Would that be fine by you @chrissimpkins ?

**Comment by chrissimpkins** [comment]
Probably worth checking to see if we confuse applications that use STAT by keeping irrelevant data in, even if it is acceptable according to the OT spec.  Though, it isn't clear to me what application environments of any importance to us use STAT data.  Can you think of important test cases to have a look?

Also, I was under the impression based on discussions with Marianna in the last couple of weeks that the slicing support in fontTools removes the irrelevant STAT data following axis range changes and instancing.  I take it we do not have that support in fontTools?  Should we?

**Comment by MariannaPaszkowska** [comment]
Yes, I also expected this data to be sliced off.
We can investigate!

**Comment by belluzj** [comment]
FontTools does remove "irrelevant" entries in that it removes AxisValues that are not part of the selected range/single location for each axis. But it doesn't remove the axis itself. I can go ask in the engineering chat if that's as expected.

Again, I can delete the entries from the Workspace fonts as well, if that can avoid a costly round of investigation.

**Comment by Lorp** [comment]
Sounds good to me that the axis itself remains in STAT, indicating that the font can play a role among other "sliced" fonts.

For example, you could take 3 wdth slices from a wght/wdth font (say wdth=70, wdth=85, wdth=100), each retaining a full wght axis. The wdth axis setting of 70 should be recorded in the first font’s STAT, 85 in the second font’s STAT, 100 in the 3rd font’s STAT. Then an application could reasonably offer a wdth axis control (as well as wght) where the app uses the font with STAT wdth closest to selected wdth. Whether any apps do this is another matter of course.

**Comment by chrissimpkins** [comment]
Thanks all.  Given that these are **only** meant for use in Workspace editors and the editors do not use STAT (or VFs for that matter...), I think that we are ok to ship these fonts as is.  No need to do further testing.  But we should keep these restricted to WS editor use, or do additional testing if we decide to broaden the use cases down the road. They are only variable to future-proof the format for eventual WS editor VF support.  They'll get them as statics instanced by our internal pipeline.

**Comment by belluzj** [comment]
After Marianna requested testing in Adobe apps, we found that indeed having more STAT entries than necessary seems to break the fonts in InDesign on Mac. PR for cleaning up the STAT: #951
