### ISSUE TITLE
Outline artifact in numeral nine, thin weights

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/googlesans-flex#954]
Report from Ryan Kiley on the Material UX team based on our latest v2.000 release build:

Odd joint noticed in Google Sans Flex's number 9 at thinner weights (especially weight 100). The "joint" seems to accentuate at larger font sizes, but was still noticeable at smaller font sizes too. Screenshot attached.

Example: https://www.figma.com/design/NgpwOsppto3Nx1mq5hH5Ao/BC25-Android-Status-Bar-Iconography?node-id=2905-10349&t=VUaypzo3O6bt1xdj-1

```
font-size: 220px;
font-style: normal;
font-weight: 100;
line-height: 220px; /* 100% */
letter-spacing: -8.8px;
```

<img width="383" alt="345290371__56945437__43094" src="https://github.com/googlefonts/googlesans-flex/assets/4249591/1acec8ea-9ad1-46fd-b2e5-9176662fb034">

Possible to address this in the v2.003 release if it hasn't already been addressed?

---

b/345290371

**Comment by davelab6** [comment]
@behdad @simoncozens do you think there could be automated ways to detect this issue?

**Comment by simoncozens** [comment]
First thought: we could use boolean operations to divide the glyph into overlaps:

<img width="287" alt="Screenshot 2024-06-06 at 17 47 58" src="https://github.com/googlefonts/googlesans-flex/assets/106728/d03d299b-764c-4715-8264-1d7bafee549a">

And then categorise the overlaps (blue number 4 is fully internal, light green number 3 is external, etc.) An external overlap with a small area is probably a mistake.

**Comment by MariannaPaszkowska** [comment]
@behdad maybe we could add a test like this to the varLib/interpolatable? 

I opened an issue here: https://github.com/fonttools/fonttools/issues/3562

**Comment by simoncozens** [comment]
I have another potential way to check this which doesn't involve *too much* messing around with boolean ops:

1. Measure the average difference in curvature and tangent between in-segments and out-segments at each node.
2. Remove overlaps
3. Measure again.

If the average increases, something weird has happened.

**Comment by simoncozens** [comment]
I've implemented this, and somewhat unsurprisingly it's found a problem with the `six` as well.

```
$ ./target/release/overlapnanny GoogleSansFlex\[GRAD,ROND,opsz,slnt,wdth,wght\].ttf --tolerance 2
Testing instance Thin (opsz=18 wdth=100 wght=100 GRAD=0 ROND=0 slnt=0 )
 Wonkiness increased by 341.33% in glyph six
 Wonkiness increased by 341.69% in glyph nine
 Wonkiness increased by 374.75% in glyph notequal
 Wonkiness increased by 343.80% in glyph nine.tf
```

**Comment by behdad** [comment]
Cool! How does it work? Where's the code?

**Comment by simoncozens** [comment]
It's at https://github.com/simoncozens/overlapnanny

The idea is to take a measure of "wonkiness" of a glyph; this is the sum, for each node in a path, of combination of the difference between incoming angle / outgoing angle and the incoming curvature / outgoing curvature; so it should give a sense of whether there are bumps and kinks in the path. Then we feed it to `skia::simplify` to remove overlaps, and then take the measure again. If the wonkiness has increased a lot, there may be a problem with the glyph.

There are a bunch of false positives because it doesn't like certain constructions, so I need to improve the measure, but it's something. (Here's an example of a false positive:

<img width="287" alt="Screenshot 2024-06-12 at 15 04 24" src="https://github.com/googlefonts/googlesans-flex/assets/106728/c2509e1c-cd3f-4a22-8bae-5dd2f1287f79">

Each path is perfectly un-wonky by itself, but when you remove overlaps, you get sharp corners that it doesn't like.)

**Comment by anthrotype** [comment]
> If the wonkiness has increased a lot, there may be a problem with the glyph.

or a bug in skia pathops which is equally likely 😅

**Comment by davelab6** [comment]
@felipesanches @simoncozens do you think this can become a FB check for the general case?

@octaviopardo @MariannaPaszkowska how to resolve for the specific case of this family? @chrissimpkins asked on chat "Can we slot this into v2.003 if it hasn't already been fixed?" which I think is important to answer, and hoping affirmatively :)

**Comment by chrissimpkins** [comment]
The fix is in progress and should be in place by next week.  We'll have a test font for Ryan to verify based on my discussion with Octavio today.

**Comment by octaviopardo** [comment]
Issue fixed in the last build
https://github.com/googlefonts/googlesans-flex/actions/runs/9660751975


https://github.com/googlefonts/googlesans-flex/assets/2181684/c50a5f6a-fdad-4cdc-a4c1-bfd4c0afaace

**Comment by chrissimpkins** [comment]
Ryan verified the fix.  Let's please include this in the v2.3 release.  Thanks!
