### ISSUE TITLE
FB test in the import is failing: smallcaps_before_ligatures 

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#972]
com.google.fonts/check/gsub/smallcaps_before_ligatures: FAIL [missing-lookups]
in this import run:
https://github.com/googlefonts/googlesans-flex/actions/runs/9973387554/job/27559151173

https://github.com/fonttools/fontbakery/blob/main/CHANGELOG.md

The issue is that we don't include smallcaps in GSF. It seems that this check was fixed by @m4rc1e but afaiu, the fix has not been released yet https://github.com/fonttools/fontbakery/pull/4787 is that right?

@felipesanches @simoncozens When is the FB release planned?

**Comment by MariannaPaszkowska** [comment]
In the meantime perhaps we can pin the FB to the release before this check was introduced @RickyDaMa ? Any thoughts?

**Comment by simoncozens** [comment]
@felipesanches I'm starting to wonder if we should have `--skip-experimental` (or skip them by default and add `--experimental` to run them).

**Comment by RickyDaMa** [comment]
> I'm starting to wonder if we should have `--skip-experimental`

If that check is considered experimental currently that would be really useful. I understand why you'd want them on by default, but having the ability to disable them would be great for sensitive projects like this. Plus then we have control and don't need 'third party' support in order to get around such issues

If Fontbakery isn't imminently releasing, we could either exclude this check until the fix is released (preferred), or pin to an older Fontbakery as you suggest

**Comment by MariannaPaszkowska** [comment]
Let's exclude this check and open an issue for v3.000 to revisit including it.

**Comment by MariannaPaszkowska** [comment]
@simoncozens I like the idea of having --skip-experimental argument!

**Comment by RickyDaMa** [comment]
> open an issue for v3.000

#976. PR incoming to exclude it

**Comment by felipesanches** [comment]
https://github.com/fonttools/fontbakery/pull/4796

**Comment by felipesanches** [comment]
New FontBakery v0.12.9 is now released, including the fix to this check.

https://pypi.org/project/fontbakery/0.12.9/

You should consider now removing it from "exclude_checks" in your QA setup so that, in case the font project evolves in the future to include smallcaps, it will automatically be covered by the check.

**Comment by RickyDaMa** [comment]
Thanks Felipe, this is covered by #976, so I'll leave this issue closed
